%ifndef GUARD_CRYPTO_USIGN_ED25519_FE25519_ASM
%define GUARD_CRYPTO_USIGN_ED25519_FE25519_ASM
; =============================================================================
; Tattva OS — crypto/usign/ed25519/fe25519.asm
; =============================================================================
; Field arithmetic modulo p = 2^255 - 19.
;
; Implements:
;   - Add, subtract, negate, multiply, square
;   - Canonical reduction, equality and sign tests
;   - Inversion and the square-root exponentiation Ed25519 needs
;
; REPRESENTATION: four 64-bit little-endian limbs holding any value below
; 2^256. Elements are deliberately NOT kept canonical between operations —
; carrying a value in [p, 2^256) is harmless because every operation folds the
; excess back in, and forcing a canonical form after each step would cost a
; conditional subtraction that only two functions actually need.
;
; The fold exploits 2^256 = 2 * 2^255 = 2 * (p + 19) = 38 (mod p). So whenever
; a computation overflows 256 bits, the overflow re-enters the low limb
; multiplied by 38. Every carry path below is that identity.
;
; NOT CONSTANT TIME, AND THAT IS CORRECT HERE. Signature VERIFICATION operates
; entirely on public values: the public key, the message and the signature. No
; secret is present to leak, so branching on data costs nothing and buys
; simplicity. Signing and key generation are a different matter, and this file
; must not be reused for them without a constant-time review.
;
; Author:  Utkarsha Labs
; Target:  x86-64 (64-bit NASM)
; =============================================================================

[BITS 64]

section .data
align 32

; Generated by scratchpad/ed_gen.py — computed, not transcribed.
fe25519_p_const:    dq 0xFFFFFFFFFFFFFFED, 0xFFFFFFFFFFFFFFFF, \
                       0xFFFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFF

; p - 2, the inversion exponent (Fermat: a^(p-2) = a^-1 for a != 0).
fe25519_pm2:        dq 0xFFFFFFFFFFFFFFEB, 0xFFFFFFFFFFFFFFFF, \
                       0xFFFFFFFFFFFFFFFF, 0x7FFFFFFFFFFFFFFF

; (p + 3) / 8 = 2^252 - 2. For p = 5 (mod 8), a^((p+3)/8) is a square root of
; a whenever a has one at all — but it may be off by a factor of sqrt(-1),
; which is why every caller re-checks and multiplies by sqrtm1 if needed.
fe25519_pp3d8:      dq 0xFFFFFFFFFFFFFFFE, 0xFFFFFFFFFFFFFFFF, \
                       0xFFFFFFFFFFFFFFFF, 0x0FFFFFFFFFFFFFFF

fe25519_sqrtm1:     dq 0xC4EE1B274A0EA0B0, 0x2F431806AD2FE478, \
                       0x2B4D00993DFBD7A7, 0x2B8324804FC1DF0B

fe25519_zero_const: dq 0, 0, 0, 0
fe25519_one_const:  dq 1, 0, 0, 0

section .text

global fe25519_copy
global fe25519_zero
global fe25519_one
global fe25519_add
global fe25519_sub
global fe25519_neg
global fe25519_mul
global fe25519_sq
global fe25519_reduce
global fe25519_iszero
global fe25519_eq
global fe25519_isnegative
global fe25519_pow
global fe25519_inv
global fe25519_sqrt_exp
global fe25519_sqrtm1
global fe25519_frombytes
global fe25519_tobytes

; -----------------------------------------------------------------------------
; fe25519_copy — RDI = destination, RSI = source
; -----------------------------------------------------------------------------
align 32
fe25519_copy:
    mov rax, [rsi]
    mov [rdi], rax
    mov rax, [rsi + 8]
    mov [rdi + 8], rax
    mov rax, [rsi + 16]
    mov [rdi + 16], rax
    mov rax, [rsi + 24]
    mov [rdi + 24], rax
    ret

align 32
fe25519_zero:
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax
    ret

align 32
fe25519_one:
    mov qword [rdi], 1
    xor eax, eax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax
    ret

; -----------------------------------------------------------------------------
; fe25519_add — RDI = r, RSI = a, RDX = b
;
; A carry out of the top limb is worth 2^256, which is 38 modulo p, so it comes
; back in at the bottom. The fold is applied twice: adding 38 to the low limb
; can itself carry all the way out again when the value is near 2^256.
; -----------------------------------------------------------------------------
align 32
fe25519_add:
    mov r8,  [rsi]
    add r8,  [rdx]
    mov r9,  [rsi + 8]
    adc r9,  [rdx + 8]
    mov r10, [rsi + 16]
    adc r10, [rdx + 16]
    mov r11, [rsi + 24]
    adc r11, [rdx + 24]

    mov eax, 0
    adc eax, 0
    imul eax, 38
    add r8, rax
    adc r9, 0
    adc r10, 0
    adc r11, 0

    mov eax, 0
    adc eax, 0
    imul eax, 38
    add r8, rax
    adc r9, 0
    adc r10, 0
    adc r11, 0

    mov [rdi], r8
    mov [rdi + 8], r9
    mov [rdi + 16], r10
    mov [rdi + 24], r11
    ret

; -----------------------------------------------------------------------------
; fe25519_sub — RDI = r, RSI = a, RDX = b
;
; A borrow means the 256-bit result is a - b + 2^256, and 2^256 = 38 (mod p),
; so 38 must be SUBTRACTED to land back on a - b. Adding it — the instinctive
; mirror of the carry case in fe25519_add — silently doubles the error.
; -----------------------------------------------------------------------------
align 32
fe25519_sub:
    mov r8,  [rsi]
    sub r8,  [rdx]
    mov r9,  [rsi + 8]
    sbb r9,  [rdx + 8]
    mov r10, [rsi + 16]
    sbb r10, [rdx + 16]
    mov r11, [rsi + 24]
    sbb r11, [rdx + 24]

    sbb eax, eax                    ; 0 or -1
    and eax, 38
    sub r8, rax
    sbb r9, 0
    sbb r10, 0
    sbb r11, 0

    sbb eax, eax
    and eax, 38
    sub r8, rax
    sbb r9, 0
    sbb r10, 0
    sbb r11, 0

    mov [rdi], r8
    mov [rdi + 8], r9
    mov [rdi + 16], r10
    mov [rdi + 24], r11
    ret

; -----------------------------------------------------------------------------
; fe25519_neg — RDI = r, RSI = a. Computes p - a.
; -----------------------------------------------------------------------------
align 32
fe25519_neg:
    mov rdx, rsi                    ; b = a
    lea rsi, [fe25519_p_const]      ; a = p
    jmp fe25519_sub                 ; r = p - a

; -----------------------------------------------------------------------------
; fe25519_mul — RDI = r, RSI = a, RDX = b
;
; Schoolbook 4x4 into eight limbs, then folded back with the 2^256 = 38
; identity. Aliasing r with a or b is safe: both are fully consumed into the
; stack product before anything is written back.
; -----------------------------------------------------------------------------
align 32
fe25519_mul:
    push rbx
    push r12
    push r13
    sub rsp, 64                     ; t[0..7]

    mov rbx, rdx                    ; b — RDX is clobbered by MUL

    ; ---- row 0 ----
    mov rax, [rsi]
    mul qword [rbx]
    mov [rsp], rax
    mov r8, rdx

    mov rax, [rsi]
    mul qword [rbx + 8]
    add rax, r8
    adc rdx, 0
    mov [rsp + 8], rax
    mov r8, rdx

    mov rax, [rsi]
    mul qword [rbx + 16]
    add rax, r8
    adc rdx, 0
    mov [rsp + 16], rax
    mov r8, rdx

    mov rax, [rsi]
    mul qword [rbx + 24]
    add rax, r8
    adc rdx, 0
    mov [rsp + 24], rax
    mov [rsp + 32], rdx

    ; ---- rows 1..3 ----
    ; The two-carry pattern below cannot overflow: when the high half of a
    ; product is at its maximum the low half is 1, so the two increments can
    ; never both land on the same limb at its ceiling.
%assign i 1
%rep 3
    xor r9, r9
  %assign j 0
  %rep 4
    mov rax, [rsi + i*8]
    mul qword [rbx + j*8]
    add rax, r9
    adc rdx, 0
    add [rsp + (i+j)*8], rax
    adc rdx, 0
    mov r9, rdx
  %assign j j+1
  %endrep
    mov [rsp + (i+4)*8], r9
%assign i i+1
%endrep

    ; ---- fold: r = t[0..3] + 38 * t[4..7] ----
    mov rcx, 38

    mov rax, [rsp + 32]
    mul rcx
    mov r8, rax
    mov r12, rdx

    mov rax, [rsp + 40]
    mul rcx
    add rax, r12
    adc rdx, 0
    mov r9, rax
    mov r12, rdx

    mov rax, [rsp + 48]
    mul rcx
    add rax, r12
    adc rdx, 0
    mov r10, rax
    mov r12, rdx

    mov rax, [rsp + 56]
    mul rcx
    add rax, r12
    adc rdx, 0
    mov r11, rax
    mov r13, rdx                    ; fifth limb

    add r8,  [rsp]
    adc r9,  [rsp + 8]
    adc r10, [rsp + 16]
    adc r11, [rsp + 24]
    adc r13, 0

    ; The fifth limb is below 40, so 38 times it stays inside one limb.
    mov rax, r13
    mul rcx
    add r8, rax
    adc r9, 0
    adc r10, 0
    adc r11, 0

    mov eax, 0
    adc eax, 0
    imul eax, 38
    add r8, rax
    adc r9, 0
    adc r10, 0
    adc r11, 0

    mov [rdi], r8
    mov [rdi + 8], r9
    mov [rdi + 16], r10
    mov [rdi + 24], r11

    add rsp, 64
    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; fe25519_sq — RDI = r, RSI = a
; -----------------------------------------------------------------------------
align 32
fe25519_sq:
    mov rdx, rsi
    jmp fe25519_mul

; -----------------------------------------------------------------------------
; fe25519_reduce — RDI = a, reduced in place to the canonical value in [0, p).
;
; Two bit-folds bring any value below 2^256 down under 2^255, which is p + 19,
; so a single conditional subtraction finishes the job. Skipping the second
; fold leaves values in [2^255, 2^255 + 19) unreduced, and those are exactly
; the inputs where a sign test or an equality test would then be wrong.
; -----------------------------------------------------------------------------
align 32
fe25519_reduce:
    push rbx
    push r12
    push r13
    push r14

    mov r8,  [rdi]
    mov r9,  [rdi + 8]
    mov r10, [rdi + 16]
    mov r11, [rdi + 24]

%rep 2
    mov rax, r11
    shr rax, 63
    btr r11, 63
    imul rax, rax, 19
    add r8, rax
    adc r9, 0
    adc r10, 0
    adc r11, 0
%endrep

    ; Conditionally subtract p. The four CMOVs read the borrow from the SBB
    ; chain, so nothing between them may touch the flags.
    mov rcx, 0xFFFFFFFFFFFFFFED
    mov rbx, r8
    sub rbx, rcx
    mov rcx, -1
    mov r12, r9
    sbb r12, rcx
    mov r13, r10
    sbb r13, rcx
    mov rcx, 0x7FFFFFFFFFFFFFFF
    mov r14, r11
    sbb r14, rcx

    cmovnc r8, rbx
    cmovnc r9, r12
    cmovnc r10, r13
    cmovnc r11, r14

    mov [rdi], r8
    mov [rdi + 8], r9
    mov [rdi + 16], r10
    mov [rdi + 24], r11

    pop r14
    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; fe25519_iszero — RDI = a. Returns EAX = 1 when a = 0 mod p.
;
; Reduces first: 0 and p are the same element but only one of them is all-zero
; limbs, and a raw limb test would call p nonzero.
; -----------------------------------------------------------------------------
align 32
fe25519_iszero:
    push rdi
    call fe25519_reduce
    pop rdi
    mov rax, [rdi]
    or rax, [rdi + 8]
    or rax, [rdi + 16]
    or rax, [rdi + 24]
    test rax, rax
    jz .yes
    xor eax, eax
    ret
.yes:
    mov eax, 1
    ret

; -----------------------------------------------------------------------------
; fe25519_eq — RDI = a, RSI = b. Returns EAX = 1 when equal mod p.
;
; Both operands are reduced in place; callers pass scratch copies.
; -----------------------------------------------------------------------------
align 32
fe25519_eq:
    push rbx
    push r12
    mov rbx, rdi
    mov r12, rsi

    call fe25519_reduce
    mov rdi, r12
    call fe25519_reduce

    mov rax, [rbx]
    xor rax, [r12]
    mov rcx, [rbx + 8]
    xor rcx, [r12 + 8]
    or rax, rcx
    mov rcx, [rbx + 16]
    xor rcx, [r12 + 16]
    or rax, rcx
    mov rcx, [rbx + 24]
    xor rcx, [r12 + 24]
    or rax, rcx

    test rax, rax
    jz .yes
    xor eax, eax
    pop r12
    pop rbx
    ret
.yes:
    mov eax, 1
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; fe25519_isnegative — RDI = a. Returns EAX = low bit of the canonical value.
;
; "Negative" for Ed25519 means odd. That is only well defined on the canonical
; representative, since a and a + p differ in exactly that bit.
; -----------------------------------------------------------------------------
align 32
fe25519_isnegative:
    push rdi
    call fe25519_reduce
    pop rdi
    mov eax, [rdi]
    and eax, 1
    ret

; -----------------------------------------------------------------------------
; fe25519_pow — RDI = r, RSI = a, RDX = 4-limb exponent.
;
; Square-and-multiply, most significant bit first. The exponents used here are
; fixed public constants, so the data-dependent branch is on a constant.
; -----------------------------------------------------------------------------
align 32
fe25519_pow:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 96                     ; [rsp] = accumulator, [rsp+32] = base,
                                    ; [rsp+64] = scratch

    mov r12, rdi                    ; result
    mov r13, rdx                    ; exponent

    lea rdi, [rsp + 32]
    call fe25519_copy               ; base = a

    lea rdi, [rsp]
    call fe25519_one                ; acc = 1

    mov r14d, 255                   ; bit index
.bits:
    ; acc = acc^2
    lea rdi, [rsp + 64]
    lea rsi, [rsp]
    call fe25519_sq
    lea rdi, [rsp]
    lea rsi, [rsp + 64]
    call fe25519_copy

    ; Test bit r14 of the exponent.
    mov ecx, r14d
    mov eax, ecx
    shr eax, 6                      ; limb index
    and ecx, 63                     ; bit within the limb
    mov rbx, [r13 + rax*8]
    shr rbx, cl
    test rbx, 1
    jz .next

    lea rdi, [rsp + 64]
    lea rsi, [rsp]
    lea rdx, [rsp + 32]
    call fe25519_mul
    lea rdi, [rsp]
    lea rsi, [rsp + 64]
    call fe25519_copy

.next:
    dec r14d
    jns .bits

    mov rdi, r12
    lea rsi, [rsp]
    call fe25519_copy

    add rsp, 96
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; fe25519_inv — RDI = r, RSI = a. Computes a^(p-2).
;
; Zero inverts to zero rather than failing. Every caller that cares whether the
; input was zero checks it separately; returning a bogus value here and letting
; the caller's own verification step reject it keeps the failure in one place.
; -----------------------------------------------------------------------------
align 32
fe25519_inv:
    lea rdx, [fe25519_pm2]
    jmp fe25519_pow

; -----------------------------------------------------------------------------
; fe25519_sqrt_exp — RDI = r, RSI = a. Computes a^((p+3)/8).
;
; A candidate square root, correct up to a factor of sqrt(-1). Callers must
; square the result and compare; this function cannot tell success from failure
; on its own, and treating its output as a verified root accepts points that
; are not on the curve.
; -----------------------------------------------------------------------------
align 32
fe25519_sqrt_exp:
    lea rdx, [fe25519_pp3d8]
    jmp fe25519_pow

; -----------------------------------------------------------------------------
; fe25519_frombytes — RDI = r, RSI = 32 little-endian bytes.
;
; The top bit is stripped: in Ed25519 encodings it carries the sign of x, never
; part of y.
; -----------------------------------------------------------------------------
align 32
fe25519_frombytes:
    mov rax, [rsi]
    mov [rdi], rax
    mov rax, [rsi + 8]
    mov [rdi + 8], rax
    mov rax, [rsi + 16]
    mov [rdi + 16], rax
    mov rax, [rsi + 24]
    btr rax, 63
    mov [rdi + 24], rax
    ret

; -----------------------------------------------------------------------------
; fe25519_tobytes — RDI = 32-byte output, RSI = a (reduced in place first).
; -----------------------------------------------------------------------------
align 32
fe25519_tobytes:
    push rdi
    mov rdi, rsi
    call fe25519_reduce
    pop rdi
    mov rax, [rsi]
    mov [rdi], rax
    mov rax, [rsi + 8]
    mov [rdi + 8], rax
    mov rax, [rsi + 16]
    mov [rdi + 16], rax
    mov rax, [rsi + 24]
    mov [rdi + 24], rax
    ret

%endif ; GUARD_CRYPTO_USIGN_ED25519_FE25519_ASM
