%ifndef GUARD_CRYPTO_USIGN_ED25519_GE25519_ASM
%define GUARD_CRYPTO_USIGN_ED25519_GE25519_ASM
; =============================================================================
; Tattva OS — crypto/usign/ed25519/ge25519.asm
; =============================================================================
; Group elements on the twisted Edwards curve
;   -x^2 + y^2 = 1 + d * x^2 * y^2   over GF(2^255 - 19)
;
; Implements:
;   - Point addition, which doubles correctly too (`ge25519_add`)
;   - Scalar multiplication (`ge25519_scalarmult`)
;   - Decompression and compression (`ge25519_frombytes`, `ge25519_tobytes`)
;
; EXTENDED COORDINATES (X : Y : Z : T), where x = X/Z, y = Y/Z and T = XY/Z.
; Carrying the redundant T lets addition avoid an inversion; inverting once at
; the very end, in compression, is far cheaper than inverting per operation.
;
; THE ADDITION FORMULA IS UNIFIED: it is correct for every pair of inputs on
; the curve, including a point added to itself and including the identity. That
; is a property of complete Edwards addition, and it is why there is no
; separate doubling routine here. Curves in Weierstrass form need special cases
; for P + P and P + (-P), and those special cases are a classic source of both
; wrong results and side channels. Nothing is gained by hand-optimising a
; doubling path into a verifier that runs a few hundred times a second.
;
; Author:  Utkarsha Labs
; Target:  x86-64 (64-bit NASM)
; =============================================================================

[BITS 64]

; A point is four field elements laid out X, Y, Z, T.
%define GE_X    0
%define GE_Y    32
%define GE_Z    64
%define GE_T    96
%define GE_SIZE 128

section .data
align 32

; Generated by scratchpad/ed_gen.py: d = -121665/121666 mod p.
ge25519_d:      dq 0x75EB4DCA135978A3, 0x00700A4D4141D8AB, \
                   0x8CC740797779E898, 0x52036CEE2B6FFE73

; Base point B, the generator of the prime-order subgroup.
ge25519_base_x: dq 0xC9562D608F25D51A, 0x692CC7609525A7B2, \
                   0xC0A4E231FDD6DC5C, 0x216936D3CD6E53FE
ge25519_base_y: dq 0x6666666666666658, 0x6666666666666666, \
                   0x6666666666666666, 0x6666666666666666

section .text

global ge25519_add
global ge25519_scalarmult
global ge25519_scalarmult_base
global ge25519_scalarmult_ct
global ge25519_scalarmult_base_ct
global ge25519_cmov
global ge25519_frombytes
global ge25519_tobytes
global ge25519_identity
global ge25519_base

; -----------------------------------------------------------------------------
; ge25519_identity — RDI = point. Sets (0 : 1 : 1 : 0), the neutral element.
; -----------------------------------------------------------------------------
align 32
ge25519_identity:
    push rdi
    call fe25519_zero
    mov rdi, [rsp]
    add rdi, GE_Y
    call fe25519_one
    mov rdi, [rsp]
    add rdi, GE_Z
    call fe25519_one
    mov rdi, [rsp]
    add rdi, GE_T
    call fe25519_zero
    pop rdi
    ret

; -----------------------------------------------------------------------------
; ge25519_base — RDI = point. Loads B in extended coordinates.
; -----------------------------------------------------------------------------
align 32
ge25519_base:
    push rbx
    mov rbx, rdi

    lea rsi, [ge25519_base_x]
    call fe25519_copy
    lea rdi, [rbx + GE_Y]
    lea rsi, [ge25519_base_y]
    call fe25519_copy
    lea rdi, [rbx + GE_Z]
    call fe25519_one
    lea rdi, [rbx + GE_T]
    lea rsi, [ge25519_base_x]
    lea rdx, [ge25519_base_y]
    call fe25519_mul                ; T = X * Y, since Z = 1

    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_add — RDI = r, RSI = P, RDX = Q. Computes r = P + Q.
;
;   A = (Y1-X1)(Y2-X2)      E = B - A       X3 = E * F
;   B = (Y1+X1)(Y2+X2)      F = D - C       Y3 = G * H
;   C = 2d * T1 * T2        G = D + C       T3 = E * H
;   D = 2 * Z1 * Z2         H = B + A       Z3 = F * G
;
; r may alias P, Q, or both: every input coordinate is consumed into stack
; temporaries before the first byte of the result is written. Doubling is
; therefore just ge25519_add(r, P, P), and accumulating in place is safe.
; -----------------------------------------------------------------------------
align 32
ge25519_add:
    push rbx
    push rbp
    push r12
    sub rsp, 320                    ; ten field temporaries

%define T_S0    0                   ; scratch
%define T_S1    32                  ; scratch
%define T_A     64
%define T_B     96
%define T_C     128
%define T_D     160
%define T_E     192
%define T_F     224
%define T_G     256
%define T_H     288

    mov rbx, rsi                    ; P
    mov rbp, rdx                    ; Q
    mov r12, rdi                    ; r

    ; A = (Y1 - X1) * (Y2 - X2)
    lea rdi, [rsp + T_S0]
    lea rsi, [rbx + GE_Y]
    lea rdx, [rbx + GE_X]
    call fe25519_sub
    lea rdi, [rsp + T_S1]
    lea rsi, [rbp + GE_Y]
    lea rdx, [rbp + GE_X]
    call fe25519_sub
    lea rdi, [rsp + T_A]
    lea rsi, [rsp + T_S0]
    lea rdx, [rsp + T_S1]
    call fe25519_mul

    ; B = (Y1 + X1) * (Y2 + X2)
    lea rdi, [rsp + T_S0]
    lea rsi, [rbx + GE_Y]
    lea rdx, [rbx + GE_X]
    call fe25519_add
    lea rdi, [rsp + T_S1]
    lea rsi, [rbp + GE_Y]
    lea rdx, [rbp + GE_X]
    call fe25519_add
    lea rdi, [rsp + T_B]
    lea rsi, [rsp + T_S0]
    lea rdx, [rsp + T_S1]
    call fe25519_mul

    ; C = 2 * d * T1 * T2
    lea rdi, [rsp + T_C]
    lea rsi, [rbx + GE_T]
    lea rdx, [rbp + GE_T]
    call fe25519_mul
    lea rdi, [rsp + T_C]
    lea rsi, [rsp + T_C]
    lea rdx, [ge25519_d]
    call fe25519_mul
    lea rdi, [rsp + T_C]
    lea rsi, [rsp + T_C]
    lea rdx, [rsp + T_C]
    call fe25519_add                ; doubling by self-addition

    ; D = 2 * Z1 * Z2
    lea rdi, [rsp + T_D]
    lea rsi, [rbx + GE_Z]
    lea rdx, [rbp + GE_Z]
    call fe25519_mul
    lea rdi, [rsp + T_D]
    lea rsi, [rsp + T_D]
    lea rdx, [rsp + T_D]
    call fe25519_add

    ; E, F, G, H — this is the last point at which P and Q are read.
    lea rdi, [rsp + T_E]
    lea rsi, [rsp + T_B]
    lea rdx, [rsp + T_A]
    call fe25519_sub
    lea rdi, [rsp + T_F]
    lea rsi, [rsp + T_D]
    lea rdx, [rsp + T_C]
    call fe25519_sub
    lea rdi, [rsp + T_G]
    lea rsi, [rsp + T_D]
    lea rdx, [rsp + T_C]
    call fe25519_add
    lea rdi, [rsp + T_H]
    lea rsi, [rsp + T_B]
    lea rdx, [rsp + T_A]
    call fe25519_add

    lea rdi, [r12 + GE_X]
    lea rsi, [rsp + T_E]
    lea rdx, [rsp + T_F]
    call fe25519_mul
    lea rdi, [r12 + GE_Y]
    lea rsi, [rsp + T_G]
    lea rdx, [rsp + T_H]
    call fe25519_mul
    lea rdi, [r12 + GE_T]
    lea rsi, [rsp + T_E]
    lea rdx, [rsp + T_H]
    call fe25519_mul
    lea rdi, [r12 + GE_Z]
    lea rsi, [rsp + T_F]
    lea rdx, [rsp + T_G]
    call fe25519_mul

    add rsp, 320
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_scalarmult — RDI = r, RSI = 32-byte little-endian scalar, RDX = P.
;
; Double-and-add, most significant bit first, accumulating into a stack copy so
; that r may alias P.
;
; The branch on each scalar bit leaks which bits are set. That is acceptable
; here and nowhere else: verification multiplies public scalars derived from
; the signature and the message hash. Signing uses ge25519_scalarmult_ct
; instead, which is why both exist — calling this one with a private scalar
; would leak it through timing while still producing a valid signature.
; -----------------------------------------------------------------------------
align 32
ge25519_scalarmult:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    sub rsp, GE_SIZE

    mov rbx, rsi                    ; scalar
    mov rbp, rdx                    ; P
    mov r12, rdi                    ; r

    mov rdi, rsp
    call ge25519_identity

    mov r13d, 255
.bits:
    mov rdi, rsp
    mov rsi, rsp
    mov rdx, rsp
    call ge25519_add                ; acc = 2 * acc

    mov ecx, r13d
    mov eax, ecx
    shr eax, 6                      ; limb
    and ecx, 63                     ; bit within the limb
    mov r14, [rbx + rax*8]
    shr r14, cl
    test r14, 1
    jz .next

    mov rdi, rsp
    mov rsi, rsp
    mov rdx, rbp
    call ge25519_add                ; acc = acc + P

.next:
    dec r13d
    jns .bits

    ; Copy the accumulator out only now, so aliasing r with P was safe.
    mov rdi, r12
    mov rsi, rsp
    mov ecx, GE_SIZE / 8
.copy:
    mov rax, [rsi]
    mov [rdi], rax
    add rsi, 8
    add rdi, 8
    dec ecx
    jnz .copy

    add rsp, GE_SIZE
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_scalarmult_base — RDI = r, RSI = 32-byte scalar.
; -----------------------------------------------------------------------------
align 32
ge25519_scalarmult_base:
    push rbx
    push r12
    sub rsp, GE_SIZE

    mov rbx, rdi
    mov r12, rsi

    mov rdi, rsp
    call ge25519_base

    mov rdi, rbx
    mov rsi, r12
    mov rdx, rsp
    call ge25519_scalarmult

    add rsp, GE_SIZE
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_cmov — RDI = r, RSI = a, RDX = mask (all ones or all zero).
;
; Sets r = a when the mask is all ones, leaves r alone when it is zero, without
; branching. The mask must be 0 or ~0, never 0 or 1: the selection is done with
; AND and OR over whole words.
; -----------------------------------------------------------------------------
align 32
ge25519_cmov:
    xor ecx, ecx
.loop:
    mov rax, [rsi + rcx*8]
    and rax, rdx                    ; a, if selected
    mov r8, [rdi + rcx*8]
    mov r9, rdx
    not r9
    and r8, r9                      ; r, if not selected
    or rax, r8
    mov [rdi + rcx*8], rax
    inc ecx
    cmp ecx, GE_SIZE / 8
    jb .loop
    ret

; -----------------------------------------------------------------------------
; ge25519_scalarmult_ct — RDI = r, RSI = 32-byte scalar, RDX = P.
;
; Constant-time scalar multiplication, for scalars that must stay secret.
;
; DOUBLE-AND-ADD-ALWAYS: every bit position performs both a doubling and an
; addition, and a masked select keeps whichever result the bit calls for. The
; variable-time version skips the addition when the bit is zero, which makes
; the running time — and the memory access pattern — a direct readout of the
; scalar. For a signing key that is the whole secret.
;
; This costs roughly twice the variable-time routine. That is the correct trade
; for signing; verification uses public scalars and keeps the fast path.
;
; Completeness of the Edwards addition law is what makes this work: there are
; no exceptional inputs to special-case, so there is nothing to branch on.
; -----------------------------------------------------------------------------
align 32
ge25519_scalarmult_ct:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 2 * GE_SIZE            ; accumulator, then the candidate sum

    mov rbx, rsi                    ; scalar
    mov rbp, rdx                    ; P
    mov r12, rdi                    ; r

    mov rdi, rsp
    call ge25519_identity

    mov r13d, 255
.bits:
    mov rdi, rsp
    mov rsi, rsp
    mov rdx, rsp
    call ge25519_add                ; acc = 2 * acc

    lea rdi, [rsp + GE_SIZE]
    mov rsi, rsp
    mov rdx, rbp
    call ge25519_add                ; candidate = acc + P, computed either way

    ; Turn the scalar bit into an all-ones or all-zero mask.
    mov ecx, r13d
    mov eax, ecx
    shr eax, 6
    and ecx, 63
    mov r14, [rbx + rax*8]
    shr r14, cl
    and r14, 1
    xor r15, r15
    sub r15, r14                    ; 0 -> 0, 1 -> all ones

    mov rdi, rsp
    lea rsi, [rsp + GE_SIZE]
    mov rdx, r15
    call ge25519_cmov

    dec r13d
    jns .bits

    mov rdi, r12
    mov rsi, rsp
    mov ecx, GE_SIZE / 8
.copy:
    mov rax, [rsi]
    mov [rdi], rax
    add rsi, 8
    add rdi, 8
    dec ecx
    jnz .copy

    add rsp, 2 * GE_SIZE
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_scalarmult_base_ct — RDI = r, RSI = 32-byte secret scalar.
; -----------------------------------------------------------------------------
align 32
ge25519_scalarmult_base_ct:
    push rbx
    push r12
    sub rsp, GE_SIZE

    mov rbx, rdi
    mov r12, rsi

    mov rdi, rsp
    call ge25519_base

    mov rdi, rbx
    mov rsi, r12
    mov rdx, rsp
    call ge25519_scalarmult_ct

    add rsp, GE_SIZE
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_frombytes — decompress a 32-byte encoding.
;
; Inputs:
;   RDI = Point to fill
;   RSI = 32 bytes: y in the low 255 bits, the sign of x in the top bit
;
; Returns:
;   EAX = 0 on success, -1 when the encoding names no point on the curve
;
; Recovers x from y via x^2 = (y^2 - 1) / (d*y^2 + 1). Because p = 5 (mod 8),
; a candidate root is x2^((p+3)/8), which is correct up to a factor of
; sqrt(-1); the result is squared and checked, and multiplied by sqrt(-1) and
; checked again before the input is accepted.
;
; EVERY REJECTION HERE MATTERS. Skipping the final square check accepts inputs
; with no square root at all, putting a value that is not on the curve into the
; group law — where the arithmetic still produces answers, just meaningless
; ones. Skipping the canonical-y check accepts two encodings of the same point.
; Skipping the x = 0 sign check accepts two encodings of the identity.
; -----------------------------------------------------------------------------
align 32
ge25519_frombytes:
    push rbx
    push rbp
    push r12
    push r13
    sub rsp, 192                    ; u, v, x2, x, t0, t1

%define F_U     0
%define F_V     32
%define F_X2    64
%define F_X     96
%define F_T0    128
%define F_T1    160

    mov rbx, rdi                    ; point
    mov rbp, rsi                    ; bytes

    ; Sign bit, taken before it is stripped.
    movzx r12d, byte [rbp + 31]
    shr r12d, 7                     ; 0 or 1

    ; y into Y, with the sign bit removed.
    lea rdi, [rbx + GE_Y]
    mov rsi, rbp
    call fe25519_frombytes

    ; Reject a non-canonical y. y and y + p encode the same field element, so
    ; accepting both would give every point two valid encodings.
    mov r8,  [rbx + GE_Y]
    mov r9,  [rbx + GE_Y + 8]
    mov r10, [rbx + GE_Y + 16]
    mov r11, [rbx + GE_Y + 24]
    mov rcx, 0xFFFFFFFFFFFFFFED
    sub r8, rcx
    mov rcx, -1
    sbb r9, rcx
    sbb r10, rcx
    mov rcx, 0x7FFFFFFFFFFFFFFF
    sbb r11, rcx
    jnc .fail                       ; no borrow means y >= p

    ; u = y^2 - 1,  v = d*y^2 + 1
    lea rdi, [rsp + F_T0]
    lea rsi, [rbx + GE_Y]
    call fe25519_sq                 ; t0 = y^2

    lea rdi, [rsp + F_T1]
    call fe25519_one
    lea rdi, [rsp + F_U]
    lea rsi, [rsp + F_T0]
    lea rdx, [rsp + F_T1]
    call fe25519_sub                ; u = y^2 - 1

    lea rdi, [rsp + F_V]
    lea rsi, [rsp + F_T0]
    lea rdx, [ge25519_d]
    call fe25519_mul                ; v = d*y^2
    lea rdi, [rsp + F_V]
    lea rsi, [rsp + F_V]
    lea rdx, [rsp + F_T1]
    call fe25519_add                ; v = d*y^2 + 1

    ; x2 = u / v
    lea rdi, [rsp + F_T0]
    lea rsi, [rsp + F_V]
    call fe25519_inv
    lea rdi, [rsp + F_X2]
    lea rsi, [rsp + F_U]
    lea rdx, [rsp + F_T0]
    call fe25519_mul

    ; x = x2^((p+3)/8)
    lea rdi, [rsp + F_X]
    lea rsi, [rsp + F_X2]
    call fe25519_sqrt_exp

    ; Check x^2 == x2.
    lea rdi, [rsp + F_T0]
    lea rsi, [rsp + F_X]
    call fe25519_sq
    lea rdi, [rsp + F_T0]
    lea rsi, [rsp + F_X2]
    call fe25519_eq
    test eax, eax
    jnz .have_root

    ; Try the other root: x * sqrt(-1).
    lea rdi, [rsp + F_X]
    lea rsi, [rsp + F_X]
    lea rdx, [fe25519_sqrtm1]
    call fe25519_mul

    lea rdi, [rsp + F_T0]
    lea rsi, [rsp + F_X]
    call fe25519_sq
    lea rdi, [rsp + F_T0]
    lea rsi, [rsp + F_X2]
    call fe25519_eq
    test eax, eax
    jz .fail                        ; x2 is not a square: not a curve point

.have_root:
    ; x = 0 has only one encoding; demanding a negative sign for it would name
    ; a point that does not exist.
    lea rdi, [rsp + F_X]
    call fe25519_iszero
    mov r13d, eax

    lea rdi, [rsp + F_X]
    call fe25519_isnegative         ; EAX = low bit of the canonical x

    test r13d, r13d
    jz .sign_check
    test r12d, r12d
    jnz .fail                       ; x = 0 but the encoding asked for -0

.sign_check:
    cmp eax, r12d
    je .sign_ok
    lea rdi, [rsp + F_X]
    lea rsi, [rsp + F_X]
    call fe25519_neg
.sign_ok:

    lea rdi, [rbx + GE_X]
    lea rsi, [rsp + F_X]
    call fe25519_copy
    lea rdi, [rbx + GE_Z]
    call fe25519_one
    lea rdi, [rbx + GE_T]
    lea rsi, [rbx + GE_X]
    lea rdx, [rbx + GE_Y]
    call fe25519_mul                ; T = X*Y with Z = 1

    xor eax, eax
    jmp .out

.fail:
    mov eax, -1

.out:
    add rsp, 192
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ge25519_tobytes — compress a point to 32 bytes.
;
; Inputs:
;   RDI = 32-byte output
;   RSI = Point
;
; Divides out Z, emits y, and folds the low bit of x into the top bit. Two
; points are equal exactly when their compressions match, which is how the
; verification equation is finally decided.
; -----------------------------------------------------------------------------
align 32
ge25519_tobytes:
    push rbx
    push rbp
    sub rsp, 96                     ; zinv, x, y

    mov rbx, rdi                    ; output
    mov rbp, rsi                    ; point

    lea rdi, [rsp]
    lea rsi, [rbp + GE_Z]
    call fe25519_inv

    lea rdi, [rsp + 32]
    lea rsi, [rbp + GE_X]
    lea rdx, [rsp]
    call fe25519_mul                ; x = X / Z

    lea rdi, [rsp + 64]
    lea rsi, [rbp + GE_Y]
    lea rdx, [rsp]
    call fe25519_mul                ; y = Y / Z

    mov rdi, rbx
    lea rsi, [rsp + 64]
    call fe25519_tobytes

    lea rdi, [rsp + 32]
    call fe25519_isnegative
    shl eax, 7
    or [rbx + 31], al

    add rsp, 96
    pop rbp
    pop rbx
    ret

%endif ; GUARD_CRYPTO_USIGN_ED25519_GE25519_ASM
