%ifndef GUARD_CRYPTO_USIGN_ED25519_SC25519_ASM
%define GUARD_CRYPTO_USIGN_ED25519_SC25519_ASM
; =============================================================================
; Tattva OS — crypto/usign/ed25519/sc25519.asm
; =============================================================================
; Scalar arithmetic modulo the group order
; L = 2^252 + 27742317777372353535851937790883648493.
;
; Implements:
;   - Reduction of a 512-bit value (`sc25519_reduce`)
;   - Canonical range check (`sc25519_lt_order`)
;   - Multi-precision helper (`sc25519_mul_limbs`)
;
; L IS NOT THE FIELD PRIME. p = 2^255 - 19 is the size of the field the curve
; is drawn in; L is the order of the subgroup the base point generates. They
; differ, and using one where the other belongs produces a verifier that
; accepts some invalid signatures — the kind of bug that never shows up on
; valid inputs.
;
; Reduction is Barrett's, because L has no exploitable shape. The field prime
; is a pseudo-Mersenne, so folding by 2^256 = 38 works there; L is not, and a
; naive fold using 2^252 = -delta would need signed intermediates that are
; awkward to keep correct in assembly. Barrett needs two multiplications and a
; precomputed constant and has no sign cases at all.
;
;   q3 = floor( floor(x / 2^192) * mu / 2^320 )     where mu = floor(2^512 / L)
;   r  = (x - q3 * L) mod 2^320
;   then subtract L while it still fits
;
; Barrett's estimate of the quotient can be short by at most two, never over,
; so the correction loop runs a bounded number of times and never has to add L
; back. Doing fewer than two corrections leaves results in [L, 3L) that look
; valid and silently break the group law downstream.
;
; Author:  Utkarsha Labs
; Target:  x86-64 (64-bit NASM)
; =============================================================================

[BITS 64]

section .data
align 32

; Generated by scratchpad/ed_gen.py.
sc25519_order:      dq 0x5812631A5CF5D3ED, 0x14DEF9DEA2F79CD6, \
                       0x0000000000000000, 0x1000000000000000, \
                       0x0000000000000000          ; padded to five limbs

sc25519_mu:         dq 0xED9CE5A30A2C131B, 0x2106215D086329A7, \
                       0xFFFFFFFFFFFFFFEB, 0xFFFFFFFFFFFFFFFF, \
                       0x000000000000000F

section .text

global sc25519_reduce
global sc25519_muladd
global sc25519_lt_order
global sc25519_mul_limbs
global sc25519_order

; -----------------------------------------------------------------------------
; sc25519_mul_limbs — schoolbook multi-precision multiply.
;
; Inputs:
;   RDI = Destination, n + m limbs
;   RSI = Operand a, ECX = n limbs
;   RDX = Operand b, R8D = m limbs
;
; Destination must not alias either operand.
; -----------------------------------------------------------------------------
align 32
sc25519_mul_limbs:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15

    mov rbx, rdx                    ; b — RDX is clobbered by MUL
    mov r12d, ecx                   ; n
    mov r13d, r8d                   ; m
    mov rbp, rdi                    ; dst

    ; Zero the destination; the inner loop accumulates into it.
    lea rdi, [rbp]
    mov ecx, r12d
    add ecx, r13d
    xor eax, eax
    rep stosq

    xor r14d, r14d                  ; i
.outer:
    cmp r14d, r12d
    jae .done

    xor r9, r9                      ; carry
    xor r15d, r15d                  ; j
.inner:
    cmp r15d, r13d
    jae .inner_done

    mov rax, [rsi + r14*8]
    mul qword [rbx + r15*8]
    add rax, r9
    adc rdx, 0

    lea rcx, [r14 + r15]
    add [rbp + rcx*8], rax
    adc rdx, 0
    mov r9, rdx

    inc r15d
    jmp .inner

.inner_done:
    lea rcx, [r14 + r13]
    mov [rbp + rcx*8], r9

    inc r14d
    jmp .outer

.done:
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; sc25519_reduce — RDI = 32-byte output, RSI = 64-byte little-endian input.
;
; Reduces a 512-bit value modulo L. This is what turns a SHA-512 digest into a
; scalar: the digest is uniform over 512 bits, and taking it modulo L is what
; makes the result uniform over the group.
; -----------------------------------------------------------------------------
align 32
sc25519_reduce:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 240                    ; q1[5]=0, q2[10]=40, q3 aliases q2+40,
                                    ; r2[9]=120, r1[5]=200

    mov rbx, rdi                    ; output
    mov rbp, rsi                    ; input

    ; ---- q1 = x >> 192, i.e. limbs 3..7 ----
%assign i 0
%rep 5
    mov rax, [rbp + (3 + i)*8]
    mov [rsp + i*8], rax
%assign i i+1
%endrep

    ; ---- q2 = q1 * mu (ten limbs) ----
    lea rdi, [rsp + 40]
    lea rsi, [rsp]
    mov ecx, 5
    lea rdx, [sc25519_mu]
    mov r8d, 5
    call sc25519_mul_limbs

    ; ---- q3 = q2 >> 320, i.e. limbs 5..9 of q2 ----
    ; Left in place at [rsp+40+40].

    ; ---- r2 = (q3 * L) truncated to five limbs ----
    lea rdi, [rsp + 120]
    lea rsi, [rsp + 80]
    mov ecx, 5
    lea rdx, [sc25519_order]
    mov r8d, 4
    call sc25519_mul_limbs

    ; ---- r1 = x mod 2^320, i.e. limbs 0..4 ----
%assign i 0
%rep 5
    mov rax, [rbp + i*8]
    mov [rsp + 200 + i*8], rax
%assign i i+1
%endrep

    ; ---- r = r1 - r2, modulo 2^320 ----
    mov r8,  [rsp + 200]
    sub r8,  [rsp + 120]
    mov r9,  [rsp + 208]
    sbb r9,  [rsp + 128]
    mov r10, [rsp + 216]
    sbb r10, [rsp + 136]
    mov r11, [rsp + 224]
    sbb r11, [rsp + 144]
    mov r12, [rsp + 232]
    sbb r12, [rsp + 152]

    ; ---- conditionally subtract L, three times ----
    ; Barrett's quotient estimate can be low by at most two, so the remainder
    ; starts below 3L. A third pass costs nothing and removes any doubt.
%rep 3
    mov rcx, [sc25519_order]
    mov r13, r8
    sub r13, rcx
    mov rcx, [sc25519_order + 8]
    mov r14, r9
    sbb r14, rcx
    mov r15, r10
    sbb r15, 0
    mov rcx, [sc25519_order + 24]
    mov rax, r11
    sbb rax, rcx
    mov rdx, r12
    sbb rdx, 0

    cmovnc r8, r13
    cmovnc r9, r14
    cmovnc r10, r15
    cmovnc r11, rax
    cmovnc r12, rdx
%endrep

    mov [rbx], r8
    mov [rbx + 8], r9
    mov [rbx + 16], r10
    mov [rbx + 24], r11

    add rsp, 240
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; sc25519_muladd — RDI = 32-byte output, RSI = a, RDX = b, RCX = c.
;
; Computes (a*b + c) mod L. This is the final step of signing:
; S = (r + k*a) mod L.
;
; a, b and c are all below L < 2^253, so a*b < 2^506 and the sum stays under
; 2^507 — it fits in eight limbs with room to spare, and no ninth limb is
; needed. Sizing this buffer by intuition rather than by that bound is how the
; carry out of the top limb gets dropped.
;
; a and c are SECRET here: a is the private scalar and c is the per-signature
; nonce. Every step below is straight-line, and the Barrett reduction it calls
; uses CMOV rather than branches, so the running time does not depend on them.
; -----------------------------------------------------------------------------
align 32
sc25519_muladd:
    push rbx
    push r12
    push r13
    sub rsp, 64                     ; 512-bit accumulator

    mov rbx, rdi                    ; out
    mov r12, rcx                    ; c

    mov rdi, rsp
    mov ecx, 4
    mov r8d, 4
    call sc25519_mul_limbs          ; a*b, eight limbs

    ; Add c, propagating the carry through the whole width.
    mov rax, [r12]
    add [rsp], rax
    mov rax, [r12 + 8]
    adc [rsp + 8], rax
    mov rax, [r12 + 16]
    adc [rsp + 16], rax
    mov rax, [r12 + 24]
    adc [rsp + 24], rax
    adc qword [rsp + 32], 0
    adc qword [rsp + 40], 0
    adc qword [rsp + 48], 0
    adc qword [rsp + 56], 0

    mov rdi, rbx
    mov rsi, rsp
    call sc25519_reduce

    add rsp, 64
    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; sc25519_lt_order — RDI = 32-byte little-endian scalar.
;
; Returns:
;   EAX = 1 when the scalar is below L, 0 otherwise
;
; Ed25519 requires the S half of a signature to be canonical. Without this
; check S and S + L both verify, so every signature has a second encoding —
; which breaks any protocol that treats a signature as a unique identifier, and
; is the malleability that RFC 8032 explicitly forbids.
; -----------------------------------------------------------------------------
align 32
sc25519_lt_order:
    mov r8,  [rdi]
    mov r9,  [rdi + 8]
    mov r10, [rdi + 16]
    mov r11, [rdi + 24]

    mov rcx, [sc25519_order]
    sub r8, rcx
    mov rcx, [sc25519_order + 8]
    sbb r9, rcx
    sbb r10, 0
    mov rcx, [sc25519_order + 24]
    sbb r11, rcx

    ; A borrow out of the top means the scalar was smaller than L.
    sbb eax, eax
    and eax, 1
    ret

%endif ; GUARD_CRYPTO_USIGN_ED25519_SC25519_ASM
