%ifndef GUARD_LIB_STR_DICT_DICT_ASM
%define GUARD_LIB_STR_DICT_DICT_ASM
; =============================================================================
; str/dict/dict.asm
; Default English dictionary — aggregator include.
;
; Part of Utkarsha Labs / Tattva OS — str library
; Arch: x86_64 | Assembler: NASM
;
; The default, always-available English dictionary for Tattva OS: exact
; lookup, prefix/autocomplete, and edit-distance spellcheck suggestions, ready
; for editors (uedit), the shell (ush tab completion), and any other consumer
; that %include's this file — no init call, no allocation, nothing to wire up
; beyond the include itself. The word data is static .rodata baked into the
; kernel image at assembly time (dict/tables/dict_table.asm, generated by
; tools/gen_dict_table.py from a SCOWL-derived wordlist; see
; data/dict/SOURCE-LICENSE.txt for that source's license).
;
; See dict/lookup.asm, dict/prefix.asm, dict/suggest.asm for the individual
; functions, and README.md in this directory for the on-disk table format
; and complexity of each operation.
; =============================================================================

%include "lib/str/dict/dict.inc"
%include "lib/str/dict/tables/dict_table.asm"
%include "lib/str/dict/lookup.asm"
%include "lib/str/dict/prefix.asm"
%include "lib/str/dict/suggest.asm"

%endif ; GUARD_LIB_STR_DICT_DICT_ASM
