%ifndef GUARD_CRYPTO_USIGN_ECDSA_ECDSA_P256_ASM
%define GUARD_CRYPTO_USIGN_ECDSA_ECDSA_P256_ASM
; =============================================================================
; Tattva OS — crypto/usign/ecdsa/ecdsa_p256.asm
; =============================================================================
; ECDSA over NIST P-256 (secp256r1) — signing and verification.
;
; Implements:
;   - Point arithmetic in Jacobian coordinates (`p256_dbl`, `p256_add`)
;   - Scalar multiplication, variable and constant time
;   - Verification (`ecdsa_p256_verify`, `ecdsa_p256_verify_der`)
;   - Signing (`ecdsa_p256_sign`, `ecdsa_p256_sign_der`)
;   - Key generation (`ecdsa_p256_keygen`)
;   - DER encode and strict decode
;
; The curve is y^2 = x^3 - 3x + b over GF(p), p = 2^256 - 2^224 + 2^192 + 2^96 - 1.
; The a = -3 choice is not cosmetic: it lets the doubling formula replace a
; multiplication by a with a subtraction, which is why every standard P-256
; implementation uses these specific formulas.
;
; JACOBIAN COORDINATES (X : Y : Z) represent the affine point (X/Z^2, Y/Z^3).
; Carrying Z avoids a modular inversion per operation; one inversion at the end
; converts back. Note the SQUARE and CUBE — treating Jacobian coordinates as if
; they were the projective (X/Z, Y/Z) kind produces points that are consistently
; wrong and no test of the group law alone will notice.
;
; VERIFICATION:
;   reject unless 1 <= r < n and 1 <= s < n
;   w  = s^-1 mod n
;   u1 = e*w mod n,  u2 = r*w mod n
;   R  = u1*G + u2*Q      (reject if the identity)
;   accept iff R.x mod n == r
;
; e IS THE LEFTMOST bitlen(n) BITS OF THE HASH, not the hash modulo n. For
; P-256 with SHA-256 both are 256 bits, so e is the whole digest read big-endian
; — but it must then be reduced mod n before use as a scalar, since a digest can
; exceed n.
;
; TWO SCALAR MULTIPLICATIONS, DELIBERATELY. `p256_scalarmult` is variable time
; and is used by verification, where every input is public. `p256_scalarmult_ct`
; is used wherever the scalar is secret — signing and key derivation. The
; difference is not an optimisation: sharing the fast one would leak the private
; key through timing while still producing perfectly valid signatures, so
; nothing would appear wrong.
;
; The variable-time addition also BRANCHES on its inputs to handle the cases the
; Jacobian formula cannot (P == Q, P == -Q, an identity operand). Those branches
; are why it cannot be reused for secrets; `p256_add_ct` computes every case and
; selects with a mask instead.
;
; NONCES ARE DETERMINISTIC (RFC 6979). ECDSA loses the private key outright if a
; nonce ever repeats, and leaks it to lattice attacks if nonces are merely
; biased. Deriving k from the key and the message removes the RNG from signing
; entirely — see rfc6979.asm.
;
; Author:  Utkarsha Labs
; Target:  x86-64 (64-bit NASM)
; =============================================================================

[BITS 64]

%include "crypto/usign/ecdsa/bn256.asm"
%include "crypto/usign/ecdsa/rfc6979.asm"

; A Jacobian point is three field elements.
%define P256_X      0
%define P256_Y      32
%define P256_Z      64
%define P256_PT     96

section .data
align 32

; Generated by scratchpad/p256_gen.py, which verifies that G lies on the curve
; and has order n before emitting anything.
global p256_p
p256_p:         dq 0xFFFFFFFFFFFFFFFF, 0x00000000FFFFFFFF, \
                   0x0000000000000000, 0xFFFFFFFF00000001
global p256_n
p256_n:         dq 0xF3B9CAC2FC632551, 0xBCE6FAADA7179E84, \
                   0xFFFFFFFFFFFFFFFF, 0xFFFFFFFF00000000
p256_b:         dq 0x3BCE3C3E27D2604B, 0x651D06B0CC53B0F6, \
                   0xB3EBBD55769886BC, 0x5AC635D8AA3A93E7
p256_gx:        dq 0xF4A13945D898C296, 0x77037D812DEB33A0, \
                   0xF8BCE6E563A440F2, 0x6B17D1F2E12C4247
p256_gy:        dq 0xCBB6406837BF51F5, 0x2BCE33576B315ECE, \
                   0x8EE7EB4A7C0F9E16, 0x4FE342E2FE1A7F9B
p256_mu_p:      dq 0x0000000000000003, 0xFFFFFFFEFFFFFFFF, \
                   0xFFFFFFFEFFFFFFFE, 0x00000000FFFFFFFF, \
                   0x0000000000000001
p256_mu_n:      dq 0x012FFD85EEDF9BFE, 0x43190552DF1A6C21, \
                   0xFFFFFFFEFFFFFFFF, 0x00000000FFFFFFFF, \
                   0x0000000000000001
p256_p_m2:      dq 0xFFFFFFFFFFFFFFFD, 0x00000000FFFFFFFF, \
                   0x0000000000000000, 0xFFFFFFFF00000001
p256_n_m2:      dq 0xF3B9CAC2FC63254F, 0xBCE6FAADA7179E84, \
                   0xFFFFFFFFFFFFFFFF, 0xFFFFFFFF00000000
p256_one:       dq 1, 0, 0, 0
p256_three:     dq 3, 0, 0, 0

section .text

global ecdsa_p256_verify
global ecdsa_p256_verify_der
global ecdsa_p256_sig_from_der
global ecdsa_p256_sig_to_der
global ecdsa_p256_sign
global ecdsa_p256_sign_der
global ecdsa_p256_keygen
global ecdsa_p256_public_from_private
global ecdsa_p256_available
global p256_scalarmult
global p256_scalarmult_ct
global p256_add_ct
global p256_add_generic
global p256_point_from_bytes

; Shorthand for arithmetic modulo the field prime.
%macro FMUL 3
    lea rdi, %1
    lea rsi, %2
    lea rdx, %3
    lea rcx, [p256_p]
    lea r8, [p256_mu_p]
    call bn256_mulmod
%endmacro
%macro FADD 3
    lea rdi, %1
    lea rsi, %2
    lea rdx, %3
    lea rcx, [p256_p]
    call bn256_addmod
%endmacro
%macro FSUB 3
    lea rdi, %1
    lea rsi, %2
    lea rdx, %3
    lea rcx, [p256_p]
    call bn256_submod
%endmacro

; -----------------------------------------------------------------------------
; ecdsa_p256_available
;
; Returns:
;   RAX = 1 — verification is implemented
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_available:
    mov rax, 1
    ret

; -----------------------------------------------------------------------------
; p256_is_infinity — RDI = Jacobian point. Returns EAX = 1 when Z is zero.
;
; The identity has no affine image, so Z = 0 is how it is represented and the
; only way to detect it.
; -----------------------------------------------------------------------------
align 32
p256_is_infinity:
    lea rdi, [rdi + P256_Z]
    jmp bn256_is_zero

; -----------------------------------------------------------------------------
; p256_dbl — RDI = r, RSI = P. Doubles a Jacobian point (a = -3).
;
;   delta = Z^2;  gamma = Y^2;  beta = X*gamma
;   alpha = 3*(X - delta)*(X + delta)        <- the a = -3 shortcut
;   X' = alpha^2 - 8*beta
;   Z' = (Y + Z)^2 - gamma - delta
;   Y' = alpha*(4*beta - X') - 8*gamma^2
; -----------------------------------------------------------------------------
align 32
p256_dbl:
    push rbx
    push rbp
    sub rsp, 224                    ; seven temporaries

%define D_DELTA  0
%define D_GAMMA  32
%define D_BETA   64
%define D_ALPHA  96
%define D_T0     128
%define D_T1     160
%define D_T2     192

    mov rbx, rsi                    ; P
    mov rbp, rdi                    ; r

    FMUL [rsp + D_DELTA], [rbx + P256_Z], [rbx + P256_Z]
    FMUL [rsp + D_GAMMA], [rbx + P256_Y], [rbx + P256_Y]
    FMUL [rsp + D_BETA],  [rbx + P256_X], [rsp + D_GAMMA]

    FSUB [rsp + D_T0], [rbx + P256_X], [rsp + D_DELTA]
    FADD [rsp + D_T1], [rbx + P256_X], [rsp + D_DELTA]
    FMUL [rsp + D_T2], [rsp + D_T0], [rsp + D_T1]
    FMUL [rsp + D_ALPHA], [rsp + D_T2], [p256_three]

    ; Z' first: it is the last use of the input Y and Z, so r may alias P.
    FADD [rsp + D_T0], [rbx + P256_Y], [rbx + P256_Z]
    FMUL [rsp + D_T0], [rsp + D_T0], [rsp + D_T0]
    FSUB [rsp + D_T0], [rsp + D_T0], [rsp + D_GAMMA]
    FSUB [rsp + D_T0], [rsp + D_T0], [rsp + D_DELTA]
    ; Held in T0 until X' and Y' are done.

    ; X' = alpha^2 - 8*beta
    FMUL [rsp + D_T1], [rsp + D_ALPHA], [rsp + D_ALPHA]
    FADD [rsp + D_T2], [rsp + D_BETA], [rsp + D_BETA]
    FADD [rsp + D_T2], [rsp + D_T2], [rsp + D_T2]
    FADD [rsp + D_T2], [rsp + D_T2], [rsp + D_T2]     ; 8*beta
    FSUB [rsp + D_T1], [rsp + D_T1], [rsp + D_T2]     ; X'

    ; Y' = alpha*(4*beta - X') - 8*gamma^2
    FADD [rsp + D_T2], [rsp + D_BETA], [rsp + D_BETA]
    FADD [rsp + D_T2], [rsp + D_T2], [rsp + D_T2]     ; 4*beta
    FSUB [rsp + D_T2], [rsp + D_T2], [rsp + D_T1]
    FMUL [rsp + D_T2], [rsp + D_T2], [rsp + D_ALPHA]

    FMUL [rsp + D_GAMMA], [rsp + D_GAMMA], [rsp + D_GAMMA]
    FADD [rsp + D_GAMMA], [rsp + D_GAMMA], [rsp + D_GAMMA]
    FADD [rsp + D_GAMMA], [rsp + D_GAMMA], [rsp + D_GAMMA]
    FADD [rsp + D_GAMMA], [rsp + D_GAMMA], [rsp + D_GAMMA]   ; 8*gamma^2
    FSUB [rsp + D_T2], [rsp + D_T2], [rsp + D_GAMMA]

    lea rdi, [rbp + P256_X]
    lea rsi, [rsp + D_T1]
    call bn256_copy
    lea rdi, [rbp + P256_Y]
    lea rsi, [rsp + D_T2]
    call bn256_copy
    lea rdi, [rbp + P256_Z]
    lea rsi, [rsp + D_T0]
    call bn256_copy

    add rsp, 224
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_add — RDI = r, RSI = P, RDX = Q. Adds two Jacobian points.
;
;   U1 = X1*Z2^2   U2 = X2*Z1^2   S1 = Y1*Z2^3   S2 = Y2*Z1^3
;   H  = U2 - U1   R  = S2 - S1
;   X3 = R^2 - H^3 - 2*U1*H^2
;   Y3 = R*(U1*H^2 - X3) - S1*H^3
;   Z3 = Z1*Z2*H
;
; This formula is INCOMPLETE. H = 0 means the points share an x coordinate, and
; then it yields either the identity (for P + -P, correctly) or all zeros (for
; P + P, incorrectly). Both cases are detected and handled explicitly below;
; omitting that check makes doubling through this path silently produce the
; point at infinity, and a verifier that hits it rejects valid signatures.
; -----------------------------------------------------------------------------
align 32
p256_add:
    push rbx
    push rbp
    push r12
    push r13
    sub rsp, 320                    ; ten temporaries

%define A_U1  0
%define A_U2  32
%define A_S1  64
%define A_S2  96
%define A_H   128
%define A_R   160
%define A_T0  192
%define A_T1  224
%define A_T2  256
%define A_T3  288

    mov rbx, rsi                    ; P
    mov r12, rdx                    ; Q
    mov rbp, rdi                    ; r

    ; If either input is the identity, the sum is the other one.
    mov rdi, rbx
    call p256_is_infinity
    test eax, eax
    jnz .p_is_inf
    mov rdi, r12
    call p256_is_infinity
    test eax, eax
    jnz .q_is_inf

    FMUL [rsp + A_T0], [r12 + P256_Z], [r12 + P256_Z]    ; Z2^2
    FMUL [rsp + A_U1], [rbx + P256_X], [rsp + A_T0]
    FMUL [rsp + A_T0], [rsp + A_T0], [r12 + P256_Z]      ; Z2^3
    FMUL [rsp + A_S1], [rbx + P256_Y], [rsp + A_T0]

    FMUL [rsp + A_T1], [rbx + P256_Z], [rbx + P256_Z]    ; Z1^2
    FMUL [rsp + A_U2], [r12 + P256_X], [rsp + A_T1]
    FMUL [rsp + A_T1], [rsp + A_T1], [rbx + P256_Z]      ; Z1^3
    FMUL [rsp + A_S2], [r12 + P256_Y], [rsp + A_T1]

    FSUB [rsp + A_H], [rsp + A_U2], [rsp + A_U1]
    FSUB [rsp + A_R], [rsp + A_S2], [rsp + A_S1]

    lea rdi, [rsp + A_H]
    call bn256_is_zero
    test eax, eax
    jz .general

    ; Same x. Equal y means this is a doubling; opposite y means the identity.
    lea rdi, [rsp + A_R]
    call bn256_is_zero
    test eax, eax
    jnz .double_instead

    ; P + (-P) = identity
    lea rdi, [rbp + P256_X]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rbp + P256_Y]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rbp + P256_Z]
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax
    jmp .out

.double_instead:
    mov rdi, rbp
    mov rsi, rbx
    call p256_dbl
    jmp .out

.general:
    mov rdi, rbp
    mov rsi, rbx
    mov rdx, r12
    call p256_add_generic
    jmp .out

.p_is_inf:
    mov rdi, rbp
    mov rsi, r12
    mov ecx, P256_PT / 8
    call p256_copy_pt
    jmp .out

.q_is_inf:
    mov rdi, rbp
    mov rsi, rbx
    mov ecx, P256_PT / 8
    call p256_copy_pt

.out:
    add rsp, 320
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_add_generic — RDI = r, RSI = P, RDX = Q.
;
; The Jacobian addition formula with NO case analysis. Correct only when P and
; Q are distinct, non-opposite, and neither is the identity. Callers are
; responsible for those cases: p256_add branches on them, p256_add_ct computes
; the alternatives and selects.
;
;   X3 = R^2 - H^3 - 2*U1*H^2
;   Y3 = R*(U1*H^2 - X3) - S1*H^3
;   Z3 = Z1*Z2*H
; -----------------------------------------------------------------------------
align 32
p256_add_generic:
    push rbx
    push rbp
    push r12
    sub rsp, 320

    mov rbx, rsi
    mov r12, rdx
    mov rbp, rdi

    FMUL [rsp + A_T0], [r12 + P256_Z], [r12 + P256_Z]
    FMUL [rsp + A_U1], [rbx + P256_X], [rsp + A_T0]
    FMUL [rsp + A_T0], [rsp + A_T0], [r12 + P256_Z]
    FMUL [rsp + A_S1], [rbx + P256_Y], [rsp + A_T0]

    FMUL [rsp + A_T1], [rbx + P256_Z], [rbx + P256_Z]
    FMUL [rsp + A_U2], [r12 + P256_X], [rsp + A_T1]
    FMUL [rsp + A_T1], [rsp + A_T1], [rbx + P256_Z]
    FMUL [rsp + A_S2], [r12 + P256_Y], [rsp + A_T1]

    FSUB [rsp + A_H], [rsp + A_U2], [rsp + A_U1]
    FSUB [rsp + A_R], [rsp + A_S2], [rsp + A_S1]

    FMUL [rsp + A_T0], [rsp + A_H], [rsp + A_H]          ; H^2
    FMUL [rsp + A_T1], [rsp + A_T0], [rsp + A_H]         ; H^3
    FMUL [rsp + A_T2], [rsp + A_U1], [rsp + A_T0]        ; U1*H^2

    FMUL [rsp + A_T3], [rsp + A_R], [rsp + A_R]
    FSUB [rsp + A_T3], [rsp + A_T3], [rsp + A_T1]
    FADD [rsp + A_T0], [rsp + A_T2], [rsp + A_T2]
    FSUB [rsp + A_T3], [rsp + A_T3], [rsp + A_T0]        ; X3

    FSUB [rsp + A_T0], [rsp + A_T2], [rsp + A_T3]
    FMUL [rsp + A_T0], [rsp + A_T0], [rsp + A_R]
    FMUL [rsp + A_T1], [rsp + A_S1], [rsp + A_T1]
    FSUB [rsp + A_T0], [rsp + A_T0], [rsp + A_T1]        ; Y3

    FMUL [rsp + A_T1], [rbx + P256_Z], [r12 + P256_Z]
    FMUL [rsp + A_T1], [rsp + A_T1], [rsp + A_H]         ; Z3

    lea rdi, [rbp + P256_X]
    lea rsi, [rsp + A_T3]
    call bn256_copy
    lea rdi, [rbp + P256_Y]
    lea rsi, [rsp + A_T0]
    call bn256_copy
    lea rdi, [rbp + P256_Z]
    lea rsi, [rsp + A_T1]
    call bn256_copy

    add rsp, 320
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_copy_pt — RDI = destination, RSI = source, ECX = qwords.
; -----------------------------------------------------------------------------
align 32
p256_copy_pt:
.loop:
    mov rax, [rsi]
    mov [rdi], rax
    add rsi, 8
    add rdi, 8
    dec ecx
    jnz .loop
    ret

; -----------------------------------------------------------------------------
; p256_scalarmult — RDI = r, RSI = 4-limb scalar, RDX = Jacobian point.
;
; Double-and-add, most significant bit first, accumulating in a stack copy so
; r may alias the input point.
; -----------------------------------------------------------------------------
align 32
p256_scalarmult:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    sub rsp, P256_PT

    mov rbx, rsi                    ; scalar
    mov r12, rdx                    ; P
    mov r13, rdi                    ; r

    ; Accumulator starts at the identity: (1 : 1 : 0).
    lea rdi, [rsp + P256_X]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + P256_Y]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + P256_Z]
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax

    mov ebp, 255
.bits:
    mov rdi, rsp
    mov rsi, rsp
    call p256_dbl

    mov ecx, ebp
    mov eax, ecx
    shr eax, 6
    and ecx, 63
    mov r14, [rbx + rax*8]
    shr r14, cl
    test r14, 1
    jz .next

    mov rdi, rsp
    mov rsi, rsp
    mov rdx, r12
    call p256_add

.next:
    dec ebp
    jns .bits

    mov rdi, r13
    mov rsi, rsp
    mov ecx, P256_PT / 8
    call p256_copy_pt

    add rsp, P256_PT
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_cmov_pt — RDI = r, RSI = a, RDX = mask. Branch-free point select.
; -----------------------------------------------------------------------------
align 32
p256_cmov_pt:
    push rbx
    push r12
    push r13
    mov rbx, rdi
    mov r12, rsi
    mov r13, rdx

    lea rdi, [rbx + P256_X]
    lea rsi, [r12 + P256_X]
    mov rdx, r13
    call bn256_cmov
    lea rdi, [rbx + P256_Y]
    lea rsi, [r12 + P256_Y]
    mov rdx, r13
    call bn256_cmov
    lea rdi, [rbx + P256_Z]
    lea rsi, [r12 + P256_Z]
    mov rdx, r13
    call bn256_cmov

    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_add_ct — RDI = r, RSI = P, RDX = Q. Complete, branch-free addition.
;
; The Jacobian addition formula in p256_add is incomplete: it needs special
; cases for P == Q, P == -Q, and either operand being the identity. p256_add
; detects those with branches, which is correct for verification and fatal for
; signing, where the scalar steering those branches is the private key.
;
; Here both candidate results — the generic sum and the doubling — are computed
; UNCONDITIONALLY, and a mask picks the right one:
;
;     Z1 == 0            P is the identity     -> Q
;     Z2 == 0            Q is the identity     -> P
;     H == 0, R == 0     P == Q                -> the doubling
;     H == 0, R != 0     P == -Q               -> the identity
;     otherwise                                -> the generic sum
;
; The selection order matters: the identity cases are applied LAST so they win,
; because when Z1 is zero the H and R values computed above are meaningless.
;
; Roughly twice the cost of the variable-time addition. Signing runs once per
; signature; this is not the place to economise.
; -----------------------------------------------------------------------------
align 32
p256_add_ct:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 448

%define C_GEN   0                   ; Generic sum (96)
%define C_DBL   96                  ; Doubling of P (96)
%define C_IDENT 192                 ; The identity (96)
%define C_H     288
%define C_R     320
%define C_T0    352
%define C_T1    384
%define C_T2    416

    mov rbx, rsi                    ; P
    mov r12, rdx                    ; Q
    mov rbp, rdi                    ; r

    ; ---- H and R, the discriminants ----
    FMUL [rsp + C_T0], [r12 + P256_Z], [r12 + P256_Z]      ; Z2^2
    FMUL [rsp + C_T1], [rbx + P256_X], [rsp + C_T0]        ; U1
    FMUL [rsp + C_T0], [rsp + C_T0], [r12 + P256_Z]
    FMUL [rsp + C_T2], [rbx + P256_Y], [rsp + C_T0]        ; S1

    FMUL [rsp + C_T0], [rbx + P256_Z], [rbx + P256_Z]      ; Z1^2
    FMUL [rsp + C_H], [r12 + P256_X], [rsp + C_T0]         ; U2
    FMUL [rsp + C_T0], [rsp + C_T0], [rbx + P256_Z]
    FMUL [rsp + C_R], [r12 + P256_Y], [rsp + C_T0]         ; S2

    FSUB [rsp + C_H], [rsp + C_H], [rsp + C_T1]            ; H = U2 - U1
    FSUB [rsp + C_R], [rsp + C_R], [rsp + C_T2]            ; R = S2 - S1

    ; ---- both candidates, always ----
    lea rdi, [rsp + C_GEN]
    mov rsi, rbx
    mov rdx, r12
    call p256_add_generic

    lea rdi, [rsp + C_DBL]
    mov rsi, rbx
    call p256_dbl

    ; The identity, as a constant to select.
    lea rdi, [rsp + C_IDENT + P256_X]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + C_IDENT + P256_Y]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + C_IDENT + P256_Z]
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax

    ; ---- masks ----
    lea rdi, [rsp + C_H]
    call bn256_is_zero_mask
    mov r13, rax                    ; same x
    lea rdi, [rsp + C_R]
    call bn256_is_zero_mask
    mov r14, rax                    ; same y

    ; r = generic
    mov rdi, rbp
    lea rsi, [rsp + C_GEN]
    mov ecx, P256_PT / 8
    call p256_copy_pt

    ; same x and same y -> doubling
    mov r15, r13
    and r15, r14
    mov rdi, rbp
    lea rsi, [rsp + C_DBL]
    mov rdx, r15
    call p256_cmov_pt

    ; same x, different y -> identity
    mov r15, r14
    not r15
    and r15, r13
    mov rdi, rbp
    lea rsi, [rsp + C_IDENT]
    mov rdx, r15
    call p256_cmov_pt

    ; Identity operands override everything: when Z is zero the discriminants
    ; above were computed from a point that is not really there.
    lea rdi, [r12 + P256_Z]
    call bn256_is_zero_mask
    mov rdi, rbp
    mov rsi, rbx
    mov rdx, rax
    call p256_cmov_pt               ; Q is the identity -> P

    lea rdi, [rbx + P256_Z]
    call bn256_is_zero_mask
    mov rdi, rbp
    mov rsi, r12
    mov rdx, rax
    call p256_cmov_pt               ; P is the identity -> Q

    add rsp, 448
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_scalarmult_ct — RDI = r, RSI = 4-limb secret scalar, RDX = P.
;
; Double-and-add-always over 257 bits, built entirely on p256_add_ct. Every bit
; performs the same work and the result is chosen by a mask, so neither the
; timing nor the memory access pattern depends on the scalar.
;
; 257 rather than 256 iterations because the scalar may be reduced from a wider
; value elsewhere; the extra leading zero costs one iteration and removes a
; boundary case.
; -----------------------------------------------------------------------------
align 32
p256_scalarmult_ct:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 2 * P256_PT

    mov rbx, rsi                    ; scalar
    mov r12, rdx                    ; P
    mov r13, rdi                    ; r

    ; Accumulator = identity (1 : 1 : 0)
    lea rdi, [rsp + P256_X]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + P256_Y]
    lea rsi, [p256_one]
    call bn256_copy
    lea rdi, [rsp + P256_Z]
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax

    mov ebp, 256
.bits:
    mov rdi, rsp
    mov rsi, rsp
    mov rdx, rsp
    call p256_add_ct                ; acc = 2 * acc

    lea rdi, [rsp + P256_PT]
    mov rsi, rsp
    mov rdx, r12
    call p256_add_ct                ; candidate = acc + P, computed either way

    ; Bit index 256 is always zero for a reduced scalar; guard the load.
    xor r14, r14
    cmp ebp, 256
    je .have_bit
    mov ecx, ebp
    mov eax, ecx
    shr eax, 6
    and ecx, 63
    mov r14, [rbx + rax*8]
    shr r14, cl
    and r14, 1
.have_bit:
    xor r15, r15
    sub r15, r14                    ; 0 -> 0, 1 -> all ones

    mov rdi, rsp
    lea rsi, [rsp + P256_PT]
    mov rdx, r15
    call p256_cmov_pt

    dec ebp
    jns .bits

    mov rdi, r13
    mov rsi, rsp
    mov ecx, P256_PT / 8
    call p256_copy_pt

    add rsp, 2 * P256_PT
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_from_be — RDI = 4-limb output, RSI = 32 big-endian bytes.
;
; Everything on the wire in ECDSA is big-endian; the arithmetic is
; little-endian limbs. Skipping the swap produces a byte-reversed integer,
; which is a perfectly valid number and completely the wrong one.
; -----------------------------------------------------------------------------
align 32
p256_from_be:
%assign i 0
%rep 4
    mov rax, [rsi + (3 - i)*8]
    bswap rax
    mov [rdi + i*8], rax
%assign i i+1
%endrep
    ret

; -----------------------------------------------------------------------------
; p256_point_from_bytes — RDI = Jacobian point, RSI = 64 bytes, x||y big-endian.
;
; Returns:
;   EAX = 0 on success, -1 when the point is not on the curve
;
; THE ON-CURVE CHECK IS MANDATORY. Accepting an arbitrary (x, y) lets an
; attacker supply a point on a different curve — one whose order has small
; factors — and the scalar multiplication then leaks information about the
; scalar. For verification the scalar is public, so the classic invalid-curve
; key-recovery attack does not apply, but an off-curve point also makes the
; group law meaningless, and a verifier that computes meaningless values has no
; basis for the accept it eventually issues.
; -----------------------------------------------------------------------------
align 32
p256_point_from_bytes:
    push rbx
    push rbp
    sub rsp, 128

    mov rbx, rdi
    mov rbp, rsi

    lea rdi, [rbx + P256_X]
    mov rsi, rbp
    call p256_from_be
    lea rdi, [rbx + P256_Y]
    lea rsi, [rbp + 32]
    call p256_from_be

    ; Z = 1: the input is affine.
    lea rdi, [rbx + P256_Z]
    lea rsi, [p256_one]
    call bn256_copy

    ; Coordinates must be canonical field elements.
    lea rdi, [rbx + P256_X]
    lea rsi, [p256_p]
    call bn256_cmp
    cmp eax, 0
    jge .bad
    lea rdi, [rbx + P256_Y]
    lea rsi, [p256_p]
    call bn256_cmp
    cmp eax, 0
    jge .bad

    ; y^2 == x^3 - 3x + b ?
    FMUL [rsp], [rbx + P256_Y], [rbx + P256_Y]           ; y^2
    FMUL [rsp + 32], [rbx + P256_X], [rbx + P256_X]
    FMUL [rsp + 32], [rsp + 32], [rbx + P256_X]          ; x^3
    FMUL [rsp + 64], [rbx + P256_X], [p256_three]
    FSUB [rsp + 32], [rsp + 32], [rsp + 64]              ; x^3 - 3x
    FADD [rsp + 32], [rsp + 32], [p256_b]

    lea rdi, [rsp]
    lea rsi, [rsp + 32]
    call bn256_cmp
    test eax, eax
    jnz .bad

    xor eax, eax
    jmp .out
.bad:
    mov eax, -1
.out:
    add rsp, 128
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_public_from_private
;
; Inputs:
;   RDI = 64-byte public key output, x || y big-endian
;   RSI = 32-byte private key, big-endian
;
; Returns:
;   EAX = 0 on success, -1 when the private key is out of range
;
; Uses the constant-time ladder: the scalar is the private key.
;
; The key is big-endian here to match ecdsa_p256_sign and ecdsa_p256_keygen.
; Every externally visible key and signature in this file is big-endian; the
; little-endian limb form is internal, and mixing the two silently derives a
; public key for a completely different private key.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_public_from_private:
    push rbx
    push r12
    sub rsp, 224

    mov rbx, rdi

    lea rdi, [rsp + 192]
    call p256_from_be
    lea r12, [rsp + 192]

    ; The private key must lie in [1, n-1].
    mov rdi, r12
    call bn256_is_zero
    test eax, eax
    jnz .bad
    mov rdi, r12
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jge .bad

    lea rdi, [rsp + 96]
    lea rsi, [p256_gx]
    call bn256_copy
    lea rdi, [rsp + 96 + 32]
    lea rsi, [p256_gy]
    call bn256_copy
    lea rdi, [rsp + 96 + 64]
    lea rsi, [p256_one]
    call bn256_copy

    lea rdi, [rsp]
    mov rsi, r12
    lea rdx, [rsp + 96]
    call p256_scalarmult_ct

    mov rdi, rbx
    lea rsi, [rsp]
    call p256_point_to_bytes

    xor eax, eax
    jmp .out
.bad:
    mov eax, -1
.out:
    add rsp, 224
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; p256_point_to_bytes — RDI = 64-byte output x || y big-endian, RSI = point.
;
; Converts out of Jacobian: x = X/Z^2, y = Y/Z^3. Using Z and Z^2 instead —
; the projective rather than Jacobian convention — yields a consistent but
; entirely wrong point.
; -----------------------------------------------------------------------------
align 32
p256_point_to_bytes:
    push rbx
    push rbp
    sub rsp, 128

    mov rbx, rdi
    mov rbp, rsi

    lea rdi, [rsp]
    lea rsi, [rbp + P256_Z]
    lea rdx, [p256_p_m2]
    lea rcx, [p256_p]
    lea r8, [p256_mu_p]
    call bn256_powmod                                    ; zinv

    FMUL [rsp + 32], [rsp], [rsp]                        ; zinv^2
    FMUL [rsp + 64], [rbp + P256_X], [rsp + 32]          ; x
    FMUL [rsp + 32], [rsp + 32], [rsp]                   ; zinv^3
    FMUL [rsp + 96], [rbp + P256_Y], [rsp + 32]          ; y

%assign i 0
%rep 4
    mov rax, [rsp + 64 + (3 - i)*8]
    bswap rax
    mov [rbx + i*8], rax
%assign i i+1
%endrep
%assign i 0
%rep 4
    mov rax, [rsp + 96 + (3 - i)*8]
    bswap rax
    mov [rbx + 32 + i*8], rax
%assign i i+1
%endrep

    add rsp, 128
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_keygen
;
; Inputs:
;   RDI = 32-byte private key output, big-endian
;   RSI = 64-byte public key output, x || y big-endian
;
; Returns:
;   EAX = 0 on success, -1 on failure; nothing is written on failure.
;
; Draws candidates until one lands in [1, n-1]. Reducing a random 256-bit value
; modulo n instead would bias the key toward small values, because 2^256 is not
; a multiple of n — a bias that is small but exactly the kind lattice attacks
; exploit given enough signatures.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_keygen:
    push rbx
    push r12
    push r13
    sub rsp, 64

    mov rbx, rdi                    ; Private key output
    mov r12, rsi                    ; Public key output

    test rbx, rbx
    jz .bad
    test r12, r12
    jz .bad

    xor r13d, r13d
.draw:
    lea rdi, [rsp]
    mov rsi, 32
    call urand_get_bytes
    cmp rax, 32
    jne .bad                        ; No entropy: fail, never fall back

    lea rdi, [rsp + 32]
    lea rsi, [rsp]
    call p256_from_be

    lea rdi, [rsp + 32]
    call bn256_is_zero
    test eax, eax
    jnz .again
    lea rdi, [rsp + 32]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jl .have_key

.again:
    inc r13d
    cmp r13d, 64
    jb .draw
    jmp .bad

.have_key:
    mov rdi, r12
    lea rsi, [rsp]                  ; The big-endian draw, not the limb form
    call ecdsa_p256_public_from_private
    test eax, eax
    jnz .bad

    ; Emit the private key big-endian, matching the public key convention.
    mov rdi, rbx
    lea rsi, [rsp]
    mov ecx, 32
    rep movsb

    xor eax, eax
    jmp .out
.bad:
    mov eax, -1
.out:
    ; The candidate scalar must not be left on the stack.
    lea rdi, [rsp]
    mov ecx, 8
    xor edx, edx
.wipe:
    mov [rdi], rdx
    add rdi, 8
    dec ecx
    jnz .wipe

    add rsp, 64
    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_sign
;
; Inputs:
;   RDI = 64-byte output, r || s big-endian
;   RSI = 32-byte private key, big-endian
;   RDX = Message pointer
;   RCX = Message length
;
; Returns:
;   EAX = 0 on success, -1 on failure
;
;   e = SHA-256(message), reduced mod n
;   k = RFC 6979 deterministic nonce
;   r = ([k]G).x mod n          (retry if zero)
;   s = k^-1 (e + r*d) mod n    (retry if zero)
;
; Both scalar multiplications on secret values use p256_scalarmult_ct. The
; nonce comes from the message and the key, never from the RNG — see
; rfc6979.asm for why that is the safer construction.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_sign:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 480

; G_XY is SIXTY-FOUR bytes: p256_point_to_bytes emits x || y, not just x.
; Sizing it as one coordinate silently overwrites whatever follows — which,
; laid out carelessly, is the private key.
%define G_D     0                   ; Private key as limbs
%define G_E     32                  ; Hashed message mod n
%define G_K     64                  ; Nonce
%define G_R     96
%define G_S     128
%define G_KINV  160
%define G_HASH  192                 ; 32
%define G_XY    224                 ; 64
%define G_PT    288                 ; Jacobian point (96)
%define G_BASE  384                 ; Base point (96)

    mov rbx, rdi                    ; Signature output
    mov r12, rsi                    ; Private key bytes
    mov r13, rdx                    ; Message
    mov r14, rcx                    ; Message length

    test rbx, rbx
    jz .bad
    test r12, r12
    jz .bad

    lea rdi, [rsp + G_D]
    mov rsi, r12
    call p256_from_be

    lea rdi, [rsp + G_D]
    call bn256_is_zero
    test eax, eax
    jnz .bad
    lea rdi, [rsp + G_D]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jge .bad

    ; ---- e = SHA-256(m) mod n ----
    mov rdi, r13
    mov rsi, r14
    lea rdx, [rsp + G_HASH]
    call sha256_hash

    lea rdi, [rsp + G_E]
    lea rsi, [rsp + G_HASH]
    call p256_from_be
    lea rdi, [rsp + G_E]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jl .e_ready
    lea rdi, [rsp + G_E]
    lea rsi, [rsp + G_E]
    lea rdx, [p256_n]
    lea rcx, [p256_n]
    call bn256_submod
.e_ready:

    ; ---- k ----
    lea rdi, [rsp + G_K]
    lea rsi, [rsp + G_D]
    lea rdx, [rsp + G_HASH]
    call rfc6979_generate_k

    ; ---- r = ([k]G).x mod n ----
    lea rdi, [rsp + G_BASE]
    lea rsi, [p256_gx]
    call bn256_copy
    lea rdi, [rsp + G_BASE + 32]
    lea rsi, [p256_gy]
    call bn256_copy
    lea rdi, [rsp + G_BASE + 64]
    lea rsi, [p256_one]
    call bn256_copy

    lea rdi, [rsp + G_PT]
    lea rsi, [rsp + G_K]
    lea rdx, [rsp + G_BASE]
    call p256_scalarmult_ct

    lea rdi, [rsp + G_XY]
    lea rsi, [rsp + G_PT]
    call p256_point_to_bytes        ; x || y, big-endian

    lea rdi, [rsp + G_R]
    lea rsi, [rsp + G_XY]
    call p256_from_be
    lea rdi, [rsp + G_R]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jl .r_ready
    lea rdi, [rsp + G_R]
    lea rsi, [rsp + G_R]
    lea rdx, [p256_n]
    lea rcx, [p256_n]
    call bn256_submod
.r_ready:
    lea rdi, [rsp + G_R]
    call bn256_is_zero
    test eax, eax
    jnz .bad                        ; r = 0 would discard the nonce entirely

    ; ---- s = k^-1 (e + r*d) mod n ----
    lea rdi, [rsp + G_KINV]
    lea rsi, [rsp + G_K]
    lea rdx, [p256_n_m2]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_powmod

    lea rdi, [rsp + G_S]
    lea rsi, [rsp + G_R]
    lea rdx, [rsp + G_D]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_mulmod               ; r*d

    lea rdi, [rsp + G_S]
    lea rsi, [rsp + G_S]
    lea rdx, [rsp + G_E]
    lea rcx, [p256_n]
    call bn256_addmod               ; e + r*d

    lea rdi, [rsp + G_S]
    lea rsi, [rsp + G_S]
    lea rdx, [rsp + G_KINV]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_mulmod               ; k^-1 (e + r*d)

    lea rdi, [rsp + G_S]
    call bn256_is_zero
    test eax, eax
    jnz .bad

    ; ---- emit r || s big-endian ----
%assign i 0
%rep 4
    mov rax, [rsp + G_R + (3 - i)*8]
    bswap rax
    mov [rbx + i*8], rax
%assign i i+1
%endrep
%assign i 0
%rep 4
    mov rax, [rsp + G_S + (3 - i)*8]
    bswap rax
    mov [rbx + 32 + i*8], rax
%assign i i+1
%endrep

    xor eax, eax
    jmp .out

.bad:
    mov eax, -1

.out:
    ; d, k and k^-1 all recover the private key; none may survive the call.
    lea rdi, [rsp + G_D]
    mov ecx, (G_HASH - G_D) / 8
    xor edx, edx
.scrub:
    mov [rdi], rdx
    add rdi, 8
    dec ecx
    jnz .scrub

    add rsp, 480
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_sig_to_der — encode raw r || s as DER.
;
; Inputs:
;   RDI = Output buffer, at least 72 bytes
;   RSI = 64-byte raw signature, r || s big-endian
;
; Returns:
;   EAX = Encoded length, or -1 on failure
;
; Emits the MINIMAL encoding: leading zero bytes are dropped, and a single 0x00
; is prepended only when the high bit would otherwise make the INTEGER
; negative. Any other encoding is a second valid byte string for the same
; signature, which the strict decoder in this file would reject.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_sig_to_der:
    push rbx
    push rbp
    push r12
    push r13
    push r14

    mov rbx, rdi                    ; Output
    mov rbp, rsi                    ; Raw signature

    mov byte [rbx], 0x30
    lea r12, [rbx + 2]              ; Cursor past SEQUENCE header

    xor r13d, r13d                  ; Half index
.half:
    mov r14, rbp
    mov eax, r13d
    shl eax, 5
    add r14, rax                    ; 32-byte big-endian integer

    ; Skip leading zero bytes, but never all of them.
    xor ecx, ecx
.skip:
    cmp ecx, 31
    jae .have_start
    cmp byte [r14 + rcx], 0
    jne .have_start
    inc ecx
    jmp .skip
.have_start:
    mov eax, 32
    sub eax, ecx                    ; Significant length

    mov byte [r12], 0x02
    ; Prepend 0x00 when the top bit is set, so the value stays positive.
    movzx edx, byte [r14 + rcx]
    test edx, 0x80
    jz .no_pad

    lea edx, [eax + 1]
    mov [r12 + 1], dl
    mov byte [r12 + 2], 0
    lea rdi, [r12 + 3]
    jmp .copy_int

.no_pad:
    mov [r12 + 1], al
    lea rdi, [r12 + 2]

.copy_int:
    lea rsi, [r14 + rcx]
    push rcx
    mov ecx, eax
    rep movsb
    pop rcx
    mov r12, rdi                    ; Cursor advanced by the copy

    inc r13d
    cmp r13d, 2
    jb .half

    ; Body length is everything after the two-byte header.
    mov rax, r12
    sub rax, rbx
    sub rax, 2
    mov [rbx + 1], al

    add eax, 2                      ; Total encoded length
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_sign_der — sign and emit a DER signature.
;
; Inputs:
;   RDI = Output buffer, at least 72 bytes
;   RSI = 32-byte private key, big-endian
;   RDX = Message pointer
;   RCX = Message length
;
; Returns:
;   EAX = Encoded length, or -1 on failure
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_sign_der:
    push rbx
    push r12
    sub rsp, 64

    mov rbx, rdi

    mov rdi, rsp
    call ecdsa_p256_sign
    test eax, eax
    jnz .bad

    mov rdi, rbx
    mov rsi, rsp
    call ecdsa_p256_sig_to_der
    jmp .out

.bad:
    mov eax, -1
.out:
    add rsp, 64
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_sig_from_der — convert a DER signature to raw r || s.
;
; Inputs:
;   RDI = 64-byte output, r || s big-endian
;   RSI = DER bytes
;   EDX = DER length
;
; Returns:
;   EAX = 0 on success, -1 on any malformed input
;
;   SEQUENCE { INTEGER r, INTEGER s }
;   30 <len> 02 <len> <r> 02 <len> <s>
;
; Authenticators emit ES256 signatures in this form, not as a raw pair, so a
; verifier that only accepts raw bytes rejects every real assertion.
;
; PARSING IS STRICT. Every accepted encoding of a signature is a distinct byte
; string that verifies, so a lenient parser hands out signature malleability
; for free: long-form lengths, superfluous leading zeros and trailing garbage
; would each yield a second valid encoding of the same signature. Anything
; keyed on the signature bytes — a replay cache, an audit record — is then
; trivially bypassed. DER admits exactly one encoding, and this enforces it.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_sig_from_der:
    push rbx
    push rbp
    push r12
    push r13
    push r14

    mov rbx, rdi                    ; Output
    mov rbp, rsi                    ; DER
    mov r12d, edx                   ; Length

    ; Zero the output so short integers are left-padded rather than joined to
    ; whatever the caller's buffer held.
    xor eax, eax
    mov [rbx], rax
    mov [rbx + 8], rax
    mov [rbx + 16], rax
    mov [rbx + 24], rax
    mov [rbx + 32], rax
    mov [rbx + 40], rax
    mov [rbx + 48], rax
    mov [rbx + 56], rax

    cmp r12d, 8
    jb .bad
    cmp r12d, 72                    ; 2 + 2 + 33 + 2 + 33
    ja .bad

    cmp byte [rbp], 0x30
    jne .bad

    ; Short-form length only. A P-256 signature never reaches 128 bytes, so a
    ; long-form length is by definition not the minimal encoding.
    movzx eax, byte [rbp + 1]
    lea ecx, [eax + 2]
    cmp ecx, r12d
    jne .bad                        ; Declared length must consume the input

    mov r13d, 2                     ; Cursor

    ; ---- INTEGER r ----
    lea rdi, [rbx]
    call .parse_int
    test eax, eax
    jnz .bad

    ; ---- INTEGER s ----
    lea rdi, [rbx + 32]
    call .parse_int
    test eax, eax
    jnz .bad

    cmp r13d, r12d
    jne .bad                        ; Trailing bytes

    xor eax, eax
    jmp .out

; Parses one INTEGER at R13 into the 32-byte buffer at RDI, advancing R13.
.parse_int:
    push rbx
    push r14
    mov r14, rdi

    mov eax, r13d
    inc eax
    cmp eax, r12d
    jae .pi_bad

    cmp byte [rbp + r13], 0x02
    jne .pi_bad
    inc r13d

    movzx ecx, byte [rbp + r13]     ; Content length
    inc r13d
    test ecx, ecx
    jz .pi_bad                      ; Zero-length INTEGER is not valid DER
    cmp ecx, 33
    ja .pi_bad

    mov eax, r13d
    add eax, ecx
    cmp eax, r12d
    ja .pi_bad                      ; Runs past the end

    ; A leading 0x00 is permitted only to clear a high bit that would
    ; otherwise make the value negative; anything else is non-minimal.
    cmp byte [rbp + r13], 0
    jne .pi_no_pad
    cmp ecx, 1
    je .pi_bad                      ; A bare zero is not a valid r or s
    mov eax, r13d
    inc eax
    movzx eax, byte [rbp + rax]
    test eax, 0x80
    jz .pi_bad                      ; Padding that was not needed
    inc r13d
    dec ecx
    jmp .pi_len_ok

.pi_no_pad:
    ; Without padding the high bit must be clear, or the value is negative.
    movzx eax, byte [rbp + r13]
    test eax, 0x80
    jnz .pi_bad

.pi_len_ok:
    cmp ecx, 32
    ja .pi_bad

    ; Right-align the big-endian content in the 32-byte slot.
    mov eax, 32
    sub eax, ecx
    lea rdi, [r14 + rax]
    lea rsi, [rbp + r13]
    push rcx
    rep movsb
    pop rcx
    add r13d, ecx

    xor eax, eax
    pop r14
    pop rbx
    ret

.pi_bad:
    mov eax, -1
    pop r14
    pop rbx
    ret

.bad:
    mov eax, -1

.out:
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_verify_der — verification with a DER-encoded signature.
;
; Inputs:
;   RDI = 64-byte public key, x || y, big-endian
;   RSI = Message pointer
;   RDX = Message length
;   RCX = DER signature
;   R8D = DER signature length
;
; Returns:
;   RAX = 1 when valid, 0 otherwise
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_verify_der:
    push rbx
    push r12
    push r13
    sub rsp, 64

    mov rbx, rdi
    mov r12, rsi
    mov r13, rdx

    mov rdi, rsp
    mov rsi, rcx
    mov edx, r8d
    call ecdsa_p256_sig_from_der
    test eax, eax
    jnz .bad

    mov rdi, rbx
    mov rsi, r12
    mov rdx, r13
    mov rcx, rsp
    call ecdsa_p256_verify
    jmp .out

.bad:
    xor eax, eax

.out:
    add rsp, 64
    pop r13
    pop r12
    pop rbx
    ret

; -----------------------------------------------------------------------------
; ecdsa_p256_verify
;
; Inputs:
;   RDI = 64-byte public key, x || y, big-endian
;   RSI = Message pointer
;   RDX = Message length
;   RCX = 64-byte signature, r || s, big-endian
;
; Returns:
;   RAX = 1 when the signature is valid, 0 otherwise
;
; The message is hashed here with SHA-256, matching COSE ES256. Callers that
; already hold a digest must not pass it in as the message — it would be hashed
; a second time.
; -----------------------------------------------------------------------------
align 32
ecdsa_p256_verify:
    push rbx
    push rbp
    push r12
    push r13
    push r14
    push r15
    sub rsp, 576

%define V_Q     0                   ; Public key point (96)
%define V_R1    96                  ; u1*G (96)
%define V_R2    192                 ; u2*Q (96)
%define V_r     288
%define V_s     320
%define V_e     352
%define V_w     384
%define V_u1    416
%define V_u2    448
%define V_hash  480
%define V_tmp   512

    mov rbx, rdi                    ; Public key
    mov r12, rsi                    ; Message
    mov r13, rdx                    ; Message length
    mov r14, rcx                    ; Signature

    test rbx, rbx
    jz .bad
    test r14, r14
    jz .bad

    ; ---- r and s must be in [1, n-1] ----
    lea rdi, [rsp + V_r]
    mov rsi, r14
    call p256_from_be
    lea rdi, [rsp + V_s]
    lea rsi, [r14 + 32]
    call p256_from_be

    lea rdi, [rsp + V_r]
    call bn256_is_zero
    test eax, eax
    jnz .bad
    lea rdi, [rsp + V_s]
    call bn256_is_zero
    test eax, eax
    jnz .bad

    lea rdi, [rsp + V_r]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jge .bad                        ; r >= n is not a canonical signature
    lea rdi, [rsp + V_s]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jge .bad

    ; ---- public key must be a point on the curve ----
    lea rdi, [rsp + V_Q]
    mov rsi, rbx
    call p256_point_from_bytes
    test eax, eax
    jnz .bad

    ; ---- e = SHA-256(message), reduced mod n ----
    mov rdi, r12
    mov rsi, r13
    lea rdx, [rsp + V_hash]
    call sha256_hash

    lea rdi, [rsp + V_e]
    lea rsi, [rsp + V_hash]
    call p256_from_be

    ; A digest can exceed n, so it must be reduced before use as a scalar.
    lea rdi, [rsp + V_e]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jl .e_ready
    lea rdi, [rsp + V_e]
    lea rsi, [rsp + V_e]
    lea rdx, [p256_n]
    lea rcx, [p256_n]
    call bn256_submod
.e_ready:

    ; ---- w = s^-1 mod n ----
    lea rdi, [rsp + V_w]
    lea rsi, [rsp + V_s]
    lea rdx, [p256_n_m2]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_powmod

    ; ---- u1 = e*w, u2 = r*w, both mod n ----
    lea rdi, [rsp + V_u1]
    lea rsi, [rsp + V_e]
    lea rdx, [rsp + V_w]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_mulmod

    lea rdi, [rsp + V_u2]
    lea rsi, [rsp + V_r]
    lea rdx, [rsp + V_w]
    lea rcx, [p256_n]
    lea r8, [p256_mu_n]
    call bn256_mulmod

    ; ---- R = u1*G + u2*Q ----
    lea rdi, [rsp + V_tmp]
    lea rsi, [p256_gx]
    call bn256_copy
    lea rdi, [rsp + V_tmp + 32]
    lea rsi, [p256_gy]
    call bn256_copy
    lea rdi, [rsp + V_tmp + 64]
    lea rsi, [p256_one]
    call bn256_copy

    lea rdi, [rsp + V_R1]
    lea rsi, [rsp + V_u1]
    lea rdx, [rsp + V_tmp]
    call p256_scalarmult

    lea rdi, [rsp + V_R2]
    lea rsi, [rsp + V_u2]
    lea rdx, [rsp + V_Q]
    call p256_scalarmult

    lea rdi, [rsp + V_R1]
    lea rsi, [rsp + V_R1]
    lea rdx, [rsp + V_R2]
    call p256_add

    lea rdi, [rsp + V_R1]
    call p256_is_infinity
    test eax, eax
    jnz .bad                        ; No x coordinate to compare against r

    ; ---- convert R back to affine x and compare with r ----
    lea rdi, [rsp + V_tmp]
    lea rsi, [rsp + V_R1 + P256_Z]
    lea rdx, [p256_p_m2]
    lea rcx, [p256_p]
    lea r8, [p256_mu_p]
    call bn256_powmod               ; zinv

    FMUL [rsp + V_tmp + 32], [rsp + V_tmp], [rsp + V_tmp]        ; zinv^2
    FMUL [rsp + V_tmp], [rsp + V_R1 + P256_X], [rsp + V_tmp + 32]

    ; v = x mod n
    lea rdi, [rsp + V_tmp]
    lea rsi, [p256_n]
    call bn256_cmp
    cmp eax, 0
    jl .compare
    lea rdi, [rsp + V_tmp]
    lea rsi, [rsp + V_tmp]
    lea rdx, [p256_n]
    lea rcx, [p256_n]
    call bn256_submod

.compare:
    lea rdi, [rsp + V_tmp]
    lea rsi, [rsp + V_r]
    call bn256_cmp
    test eax, eax
    jnz .bad

    mov rax, 1
    jmp .out

.bad:
    xor eax, eax

.out:
    add rsp, 576
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbp
    pop rbx
    ret

%endif ; GUARD_CRYPTO_USIGN_ECDSA_ECDSA_P256_ASM
