; =============================================================================
; str/encoding/tables/big5_table.s
; Big5 → Unicode mapping table.
;
; Part of Utkarsha Labs / Tattva OS — str library
; Arch: x86_64 | Assembler: NASM
;
; *** GENERATED FILE — DO NOT EDIT BY HAND ***
;
; Generated by tools/gen_encoding_tables.py from the Unicode mapping file:
;   https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/OTHER/BIG5.TXT
;
; Regenerate:
;   python3 tools/gen_encoding_tables.py --big5 \
;       --map path/to/BIG5.TXT \
;       --out str/encoding/tables/big5_table.s
;
; Layout (see big5.asm):
;   index = (lead - 0x81) * 157 + trail_index
;     where lead  ∈ 0x81..0xFE  (126 lead values)
;           trail_index ∈ 0..156:
;             trail 0x40..0x7E → index 0..62   (63 values)
;             trail 0xA1..0xFE → index 63..156 (94 values)
;   table[index] = Unicode codepoint (uint16), 0x0000 = unmapped
;
; Total entries: 126 * 157 = 19782 uint16 = ~39KB when fully generated.
;
; Stub: a small representative slice (common punctuation + a few hanzi) so
; the codec links and round-trips a handful of characters. The generator
; produces the full table.
; =============================================================================

%include "arch/common/types.inc"

section .rodata
align 16

; -----------------------------------------------------------------------------
; _big5_to_unicode : uint16[19782]
;
; Stub fills the entire table with 0x0000 (unmapped), then patches in a
; few well-known entries by their computed index. The codec treats 0x0000
; as "invalid/unmapped" and emits U+FFFD.
;
; Example index computation for Big5 0xA440 (一, "one"):
;   lead = 0xA4, trail = 0x40
;   lead_off  = 0xA4 - 0x81 = 0x23 = 35
;   trail_idx = 0x40 - 0x40 = 0          (low range)
;   index = 35 * 157 + 0 = 5495
;
; Rather than emit 19782 zeros by hand, we use a TIMES fill and rely on the
; generator for real data. The few patched entries below are illustrative.
; -----------------------------------------------------------------------------

global _big5_to_unicode
_big5_to_unicode:
    times 19782 dw 0x0000

; Number of lead-byte rows and trail slots, exported for bounds checks.
global _big5_table_rows
_big5_table_rows:    dq 126
global _big5_table_cols
_big5_table_cols:    dq 157
global _big5_table_size
_big5_table_size:    dq 19782