; =============================================================================
; str/encoding/tables/euc_kr_table.s
; EUC-KR (KS X 1001) → Unicode mapping table.
;
; Part of Utkarsha Labs / Tattva OS — str library
; Arch: x86_64 | Assembler: NASM
;
; *** GENERATED FILE — DO NOT EDIT BY HAND ***
;
; Generated by tools/gen_encoding_tables.py from the Unicode mapping file:
;   https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/KSC/KSC5601.TXT
;
; Regenerate:
;   python3 tools/gen_encoding_tables.py --euc-kr \
;       --map path/to/KSC5601.TXT \
;       --out str/encoding/tables/euc_kr_table.s
;
; Layout (see euc_kr.asm):
;   EUC-KR (KS X 1001): lead 0xA1..0xFE, trail 0xA1..0xFE
;   index = (lead - 0xA1) * 94 + (trail - 0xA1)
;   table[index] = Unicode codepoint (uint16), 0x0000 = unmapped
;
;   The 94×94 grid = 8836 entries = ~17KB.
;
; Note: EUC-KR proper covers 2350 precomposed Hangul syllables + Hanja +
; symbols. The CP949 / UHC superset (Windows codepage 949) extends the lead
; range to 0x81..0xFE and adds the remaining 8822 modern Hangul syllables;
; euc_kr.asm implements EUC-KR proper, and a CP949 variant can reuse this
; table plus an extension block generated with --cp949.
;
; Stub: all-zero 94×94 grid. Generator fills with real KS X 1001 mappings.
; =============================================================================

%include "arch/common/types.inc"

section .rodata
align 16

; -----------------------------------------------------------------------------
; _euckr_to_unicode : uint16[8836]  (94 × 94, KS X 1001)
;
; Example index for EUC-KR 0xB0A1 (가, Hangul GA):
;   lead = 0xB0, trail = 0xA1
;   index = (0xB0 - 0xA1) * 94 + (0xA1 - 0xA1) = 15 * 94 + 0 = 1410
;   table[1410] should be 0xAC00 (가)
; -----------------------------------------------------------------------------

global _euckr_to_unicode
_euckr_to_unicode:
    times 8836 dw 0x0000

global _euckr_table_rows
_euckr_table_rows:   dq 94
global _euckr_table_cols
_euckr_table_cols:   dq 94
global _euckr_table_size
_euckr_table_size:   dq 8836