; =============================================================================
; str/encoding/tables/euc_jp_table.s
; EUC-JP (JIS X 0208) → Unicode mapping table.
;
; Part of Utkarsha Labs / Tattva OS — str library
; Arch: x86_64 | Assembler: NASM
;
; *** GENERATED FILE — DO NOT EDIT BY HAND ***
;
; Generated by tools/gen_encoding_tables.py from the Unicode mapping file:
;   https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT
;
; Regenerate:
;   python3 tools/gen_encoding_tables.py --euc-jp \
;       --map path/to/JIS0208.TXT \
;       --out str/encoding/tables/euc_jp_table.s
;
; Layout (see euc_jp.asm):
;   EUC-JP code set 1 (JIS X 0208): lead 0xA1..0xFE, trail 0xA1..0xFE
;   index = (lead - 0xA1) * 94 + (trail - 0xA1)
;   table[index] = Unicode codepoint (uint16), 0x0000 = unmapped
;
;   The 94×94 grid = 8836 entries = ~17KB.
;
;   A supplementary section at offset >= 94*94 holds JIS X 0212 (code set 3,
;   accessed via SS3 0x8F prefix) if the generator is run with --jisx0212.
;
; Note: EUC-JP also has:
;   - code set 0: ASCII (0x00-0x7F) — handled directly in euc_jp.asm
;   - code set 2: half-width katakana (SS2 0x8E + 0xA1-0xDF) — algorithmic
;     (maps to U+FF61..U+FF9F), handled in euc_jp.asm without this table
;
; Stub: all-zero 94×94 grid. Generator fills with real JIS X 0208 mappings.
; =============================================================================

%include "arch/common/types.inc"

section .rodata
align 16

; -----------------------------------------------------------------------------
; _eucjp_to_unicode : uint16[8836]  (94 × 94, code set 1 = JIS X 0208)
;
; Example index for EUC-JP 0xA4A2 (あ, hiragana A):
;   lead = 0xA4, trail = 0xA2
;   index = (0xA4 - 0xA1) * 94 + (0xA2 - 0xA1) = 3 * 94 + 1 = 283
;   table[283] should be 0x3042 (あ)
; -----------------------------------------------------------------------------

global _eucjp_to_unicode
_eucjp_to_unicode:
    times 8836 dw 0x0000

global _eucjp_table_rows
_eucjp_table_rows:   dq 94
global _eucjp_table_cols
_eucjp_table_cols:   dq 94
global _eucjp_table_size
_eucjp_table_size:   dq 8836