; =============================================================================
; str/encoding/tables/gbk_table.s
; GBK → Unicode mapping table.
;
; Part of Utkarsha Labs / Tattva OS — str library
; Arch: x86_64 | Assembler: NASM
;
; *** GENERATED FILE — DO NOT EDIT BY HAND ***
;
; Generated by tools/gen_encoding_tables.py from:
;   https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP936.TXT
;
; Regenerate:
;   python3 tools/gen_encoding_tables.py --gbk \
;       --map path/to/CP936.TXT \
;       --out str/encoding/tables/gbk_table.s
;
; Layout (see encoding/gbk.asm):
;   lead:  0x81-0xFE  (126 values)
;   trail: 0x40-0x7E → index 0..62  (63 values)
;          0x80-0xFE → index 63..189 (127 values)
;   total trail slots per lead: 190
;   index = (lead - 0x81) * 190 + trail_index
;   table[index] = uint16 Unicode codepoint, 0x0000 = unmapped
;
; Total entries: 126 * 190 = 23940 uint16 = ~47KB
;
; Stub: all-zero. Generator fills from CP936.TXT (~21000 mappings).
; =============================================================================

%include "arch/common/types.inc"

section .rodata
align 16

global _gbk_to_unicode
_gbk_to_unicode:
    times 23940 dw 0x0000

global _gbk_table_rows
_gbk_table_rows:     dq 126
global _gbk_table_cols
_gbk_table_cols:     dq 190
global _gbk_table_size
_gbk_table_size:     dq 23940